-- Inserir dados FY720 (mantendo dados existentes)
INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
('FY 720', 'Deck Principal', 'Acesso à plataforma de popa (degraus em fibra de vidro e teca, porta de acrílico plexiglass e aço inoxidável)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Acesso à área da tripulação (gaiútas em fibra de vidro, degraus em teca)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Acesso à sala de máquinas (gaiúta, escada em aço inoxidável com degraus em teca)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Acesso ao flybridge (estrutura em fibra de vidro com degraus em teca, corrimão em aço inoxidável)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Porta deslizante na popa, com estrutura em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Área de armazenamento na popa com cobertura (abertura elétrica) (opcional)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Guincho para amarração', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Cunhos de amarração de proa em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Púlpito de proa com trilhos laterais', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Bow thruster (16hp)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Âncora modelo Bruce (50kg, corrente de 100m, diâmetro de 12mm)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Cadeiras do cockpit (4)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Iluminação indireta no cockpit', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Mesa do cockpit em teca natural e aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Defensas cilíndricas (8) e esféricas (2)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Guinchos de ancoragem elétricos 2700W com controles na proa, comando principal e comando do flybridge', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Sistema de emergência manual corta combustível (desligamento do motor e gerador, ativação do sistema de extinção de incêndio)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Alarme acústico externo para nível de água de porão', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Capas para defensas com logotipo Ferretti Yachts', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Escada de banho manual dobrável', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Guinchos elétricos com controle com acionamento no piso (2 x 700W) nos postos de amarração de popa', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Deck em fibra de vidro com superfície antiderrapante', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Chuveiro de mão com água quente/fria na plataforma de popa', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Gaiútas (2) na proa', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Plataforma de banho hidráulica (450kg)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Living na proa (sofá com armazenamento, prateleiras em teca), reversível em almofadas de solário', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Suporte para cabos de amarração na proa', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Cabos de amarração (4, com 18m cada)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Posto de amarração (2) com tampas em fibra de vidro e espaço para armazenamento de cabos', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Trilho para fechamento/capa de cobertura (cockpit)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Mangueira para a lavagem manual da ancora de proa', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Cabo para tomada de cais (230V 15m)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Porta lateral (acesso à cozinha) à Bombordo', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Pia com água doce quente/fria no posto de amarração', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Cunho de amarração de aço inoxidável: na popa (4), a meia nau (2 para cada lado) e na proa (2)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Passarela de embarque telescópica eletro-hidráulica em aço inox com controle remoto (2) e guarda corpo', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Passa cabos na popa (2) e proa (2)', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Banco com assentos no cockpit', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Paiol livre para guardar objetos', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Piso do cockpit revestido em teca', 'Padrão', 1, true, null),
('FY 720', 'Deck Principal', 'Alto-falantes a prova d''água (2)', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Porta deslizante de vidro, com estrutura de aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Ar-condicionado tropicalizado', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Armários com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Piso parquet (madeira)', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Área de living, com sofás', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Cortinas romanas nas janelas laterais', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'Cortina padrão na porta de entrada', 'Padrão', 1, true, null),
('FY 720', 'Salão', 'TV LED 43" ou equivalente', 'Padrão', 1, true, null),
('FY 720', 'Área de Jantar', 'Ar-condicionado tropicalizado', 'Padrão', 1, true, null),
('FY 720', 'Área de Jantar', 'Armário com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Área de Jantar', 'Cadeiras (8)', 'Padrão', 1, true, null),
('FY 720', 'Área de Jantar', 'Mesa de jantar para 8 pessoas', 'Padrão', 1, true, null),
('FY 720', 'Área de Jantar', 'Piso parquet (madeira)', 'Padrão', 1, true, null),
('FY 720', 'Área de Jantar', 'Cortinas romanas nas janelas laterais', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Acesso ao deck inferior (degraus de madeira)', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Ar-condicionado tropicalizado', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Armários com prateleiras e gavetas', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Cooktop de cerâmica', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Bancada', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Forno combinado elétrico/microondas', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Exaustor/coifa com saída externa (230V)', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Geladeira 198l e freezer 57l 230V-24V', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Armários superiores', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Porta lateral (acesso ao passadiço) com janela', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Pia com cobertura e torneira misturadora retrátil (água doce quente/fria)', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Louças em porcelana, copos, talheres de aço inoxidável para 8 pessoas', 'Padrão', 1, true, null),
('FY 720', 'Cozinha', 'Piso parquet (madeira)', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Ar-condicionado tropicalizado', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Controle do piloto automático', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Barômetro, relógio e higrômetro', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Tomada (12V)', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Manetes Eletrônicos para motores MAN', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Contador de corrente digital eletrônico', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Piso parquet (madeira)', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Sistema de monitoramento integrado (integrado ao sistema de navegação)', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Manual Digital Interativo no Ipad', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Bússola Magnética', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Painel elétrico principal', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Comando principal com instrumentação completa', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Instrumento de navegação multifunção', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Display touchscreen multifunção para sistema de navegação (GPS, Chartplotter, radar) (3)', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Bancos do piloto (2) com movimentação manual', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Apoio de pés reclinável', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Janela lateral com abertura elétrica', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Painel elétrico com alarmes', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Tomada USB', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'VHF', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Limpadores de pára-brisa (2) com temporizador', 'Padrão', 1, true, null),
('FY 720', 'Comando Principal', 'Capas protetoras para o para-brisas e janelas', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Acesso ao cockpit (degraus em teca e aço inoxidável, com corrimão de aço inoxidável)', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Antena radar de banda larga', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Gaiúta da escada do cockpit com corrimão de aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Iluminação de cortesia', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Capa de cobertura para o painel de comando, sofá e banco do piloto', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Painel para equipamentos de navegação diurnos', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Móvel completo com armários e pia', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Roll bar em fibra de vidro', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Coletes salva-vidas (12)', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Iluminação no flybridge', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Luzes de navegação', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Defletor frontal e lateral em acrílico', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Farol de busca manual com alcance de ½ milha (12v)', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Sofá com armazenamento (storage)', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Mastro de radar e de bandeira em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Guarda-mancebo em aço inoxidável na popa', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Solário com estofamento', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Mesa em makonil branca dobrável', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Antena de tv convencional', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Buzina de aviso com compressor', 'Padrão', 1, true, null),
('FY 720', 'Flybridge', 'Alto-falantes a prova d''água (2)', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Tomada (12V)', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Direção eletro-hidráulica assistida', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Comandos eletrônicos para motores Man', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Banco do piloto com espaço para armazenamento abaixo', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Repetidor touchscreen multifunção do sistema de navegação (GPS, plotter cartográfico, radar)', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Segundo comando, equipado com instrumentos e alarmes', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Rádio VHF', 'Padrão', 1, true, null),
('FY 720', 'Comando do Flybridge', 'Som hi-fi a prova d''água', 'Padrão', 1, true, null),
('FY 720', 'Lobby', 'Acesso à área do deck principal através de degraus de madeira', 'Padrão', 1, true, null),
('FY 720', 'Lobby', 'Carpete', 'Padrão', 1, true, null),
('FY 720', 'Lobby', 'Espaço para armazenamento embaixo escada', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Armários de cabeceira (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Armários com prateleiras (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Cama de casal com colchão, travesseiros e colcha', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Penteadeira (prateleira, espelho e pufe) com armários e prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Carpete', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Janelas do casco com vigia de aço inoxidável com abertura lateral', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Persiana black out manual', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Cortina', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Ventilação natural sob a cama', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Sofá', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Tomada de TV', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Cabeceira de cama estofada', 'Padrão', 1, true, null),
('FY 720', 'Cabine Master', 'Closet com espelho, prateleira, cofre, e armário com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Armário com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Sanitário elétrico em cerâmica', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Janela do casco com vigia abrível em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Espelhos (2)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Persiana', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Chuveiro com porta de vidro temperado e suporte em madeira', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Pia (2)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Painel de controle do WC com medidor (3/4 e completo)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro Cabine Master', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Cama de casal com colchão, travesseiros e colcha', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Gavetas embaixo da cama', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Gaiúta de emergência com escada dobrável integrada', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Carpete', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Janelas do casco (2) com vigias abríveis de aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Ventilação natural sob a cama', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Persiana manual com black out', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Cabeceira estofada', 'Padrão', 1, true, null),
('FY 720', 'Cabine VIP de Proa', 'Roupeiros (2) (com espelho, cabide, luz)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Móvel com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Sanitário elétrico em cerâmica', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Janela do casco com vigia abrível em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Persiana manual', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Espelho', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Chuveiro com porta de vidro temperado e suporte em madeira', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Pia', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Painel de controle do WC com medidor (3/4 e completo)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Cabine VIP', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Camas (2) com colchões, travesseiros e colchas', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Armário de cabeceira com gavetas', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Carpete', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Janela do casco com vigia abrível em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Ventilação natural sob as camas', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Persiana manual', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Espaço para armazenamento debaixo da cama', 'Padrão', 1, true, null),
('FY 720', 'Cabine de Hóspedes (2)', 'Guarda-roupa (com espelho, cabide, luz)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Móvel com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Sanitário elétrico em cerâmica', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Janela do casco com vigia abrível em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Espelho', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Persiana manual', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Chuveiro (com porta de vidro temperado, piso de madeira, cortina)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Pia', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Painel de controle do WC com medidor (3/4 e completo)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro de Hóspedes', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Sanitário elétrico em cerâmica', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Sistema de ventilação elétrica', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Espelho', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Armários suspensos com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Chuveiro (com piso de madeira)', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Vigia em aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Pia com água doce quente/fria', 'Padrão', 1, true, null),
('FY 720', 'Banheiro da Tripulação', 'Painel de controle do WC com medidor (3/4 e completo)', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Cama com colchão, travesseiro e colcha (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Armário de cabeceira', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Armários com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Cortina', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Carpete', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Vigia abrível de aço inoxidável', 'Padrão', 1, true, null),
('FY 720', 'Cabine da Tripulação', 'Guarda-roupa', 'Padrão', 1, true, null),
('FY 720', 'Corredor na Área da Tripulação', 'Acesso à casa de máquinas (porta estanque)', 'Padrão', 1, true, null),
('FY 720', 'Corredor na Área da Tripulação', 'Acesso à área do convés principal (degraus de teca)', 'Padrão', 1, true, null),
('FY 720', 'Corredor na Área da Tripulação', 'Armários com prateleiras', 'Padrão', 1, true, null),
('FY 720', 'Corredor na Área da Tripulação', 'Máquina seca-roupas', 'Padrão', 1, true, null),
('FY 720', 'Corredor na Área da Tripulação', 'Máquina lava-roupas', 'Padrão', 1, true, null),
('FY 720', 'Corredor na Área da Tripulação', 'Quadro elétrico principal', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Sala de máquinas', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Acesso à área da tripulação (porta estanque)', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Acesso ao cockpit (gaiúta, escada de teca e aço inoxidável)', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Entradas de ar com separador (2)', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Válvulas (2) para bombeamento de emergência de água do porão', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Bomba de esgoto elétrica', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Sistema de ventilação elétrico (2)', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Sistema de extinção de incêndio FM200 com controle automático/manual', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Torneira de água doce', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Gerador 21,5kW', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Medidor visível de nível do tanque de combustível', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Tanque de combustível GRP (4700l) com decantador e descarga integrados', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Lâmpada portátil com carretel de cabo retrátil', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Filtros do motor diesel Racor (2) com bypass + Hummel', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Pré-filtro para o combustível do gerador', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Filtro de água para sistema de refrigeração do gerador', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Filtro de água (2) para sistema de refrigeração do motor', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Aquecedor de água (80l 230V)', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Antepara dianteira estanque', 'Padrão', 1, true, null),
('FY 720', 'Área Técnica', 'Piso de madeira com superfície antiderrapante', 'Padrão', 1, true, null),
('FY 720', 'Propulsão e Controle', 'Bow thruster (16hp)', 'Padrão', 1, true, null),
('FY 720', 'Propulsão e Controle', 'Direção eletro-hidráulica - Stering System', 'Padrão', 1, true, null),
('FY 720', 'Propulsão e Controle', 'Transmissão da linha do eixo', 'Padrão', 1, true, null),
('FY 720', 'Propulsão e Controle', 'Escapes silenciadores', 'Padrão', 1, true, null),
('FY 720', 'Propulsão e Controle', 'Selos mecânicos', 'Padrão', 1, true, null),
('FY 720', 'Sistemas de Estabilização', 'Flaps - Interceptores', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Monitoramento', 'Sistema de monitoramento integrado (integrado ao sistema de navegação) com tela touchscreen (naviop)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Monitoramento', 'Controle do piloto automático (comando principal)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Monitoramento', 'Radar de banda larga', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Monitoramento', 'Display touchscreen multifunção para sistema de navegação (GPS, plotter cartográfico, radar) (3)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Monitoramento', 'Display touchscreen multifunção para sistema de navegação (GPS, chartplotter, radar) com repetidor', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Extinção de Incêndio', 'Sistema de emergência manual corta combustível', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Extinção de Incêndio', 'Sistema de extinção de incêndio FM200 na sala de máquinas, com controle automático/manual', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Extinção de Incêndio', 'Extintores de incêndio portáteis', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Extinção de Incêndio', 'Sistema de alarme de detecção de fumaça', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Sistema de ar-condicionado tropical (salão, cozinha, comando principal, cabines e banheiros)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Carregador automático de baterias 24V para baterias auxiliares de serviço', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Carregador automático de baterias 24V para baterias de motor', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Banco de baterias para carga doméstica', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Banco de baterias para partida do motor', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Chaves seccionadoras da bateria: mecânica (casa de máquinas) e eletrônica (cockpit)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Proteção catódica com anodos', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Tomadas duplas internas 120v', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Gerador 120/240V 21,5kw 60Hz', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Bateria de partida do gerador 12V', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Transformador 25kVA', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Iluminação em LED 24V', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Chave de desconexão manual da bateria para gerador', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Interruptor paralelo da bateria elétrica mecânica (cockpit)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Predisposição para instalação de TVs e decoders em todas as cabines: cabo 120V + conector F + cabos de antena de TV', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Ar Condicionado', 'Cabo de tomada de cais (100A 60Hz)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Porão', 'Bomba elétrica para drenagem do porão na sala de máquinas', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Porão', 'Bombas elétricas 4 (caixa de direção, casa de máquinas (2), espaço de alojamento)', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Porão', 'Tubo de sucção do porão de emergência (casa de máquinas) através da bomba de arrefecimento do motor', 'Padrão', 1, true, null),
('FY 720', 'Sistema de Porão', 'Bomba elétrica multiuso (porão, água cinza, água preta)', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Bomba elétrica automática para descarga do tanque de águas negras', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Bomba elétrica automática para descarga do tanque de águas cinzas', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Tanque de águas negras (350l) com medidor (3/4 e cheio)', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Sistema de sanitário elétrico com água doce', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Bomba autoclave de água doce (24V) com controle eletrônico', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Tanque de água doce (1000l)', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Tanque de águas cinzas (360l)', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Predisposição para dessalinizador', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Sistema de combate a incêndio com água do mar e lavagem da corrente', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Válvula de 3 vias na cozinha', 'Padrão', 1, true, null),
('FY 720', 'Sistemas Sanitários e de Água', 'Aquecedor de água (230V 80l)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luzes de cortesia para área interna (master, Vip, cabine de hóspedes (2) e escada de acesso ao deck inferior)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Tendalino de cobertura para a popa de flybridge', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Chuveiro removível na popa', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Stern Thruster', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Gerador auxiliar 21,5kw', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luzes de cortesia nos passadiços', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luminárias retráteis na proa (par)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luzes de cortesia na proa', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luzes de cortesia na escada de acesso ao Flybridge', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luzes de cortesia no acesso a plataforma de banho', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Piso parquet no deck principal (salão, área de jantar, cozinha e comando principal)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Revestimento em teca no Flybridge', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Lixeira no cockpit', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Entrada de água doce de cais', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Separador de fumaça para os geradores', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Upgrade de telas Simrad - Monitores EVO3 no comando principal 4 x 16", e Monitores EVO3 no comando do Flybridge, 2 x 12''''', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Cortinas elétricas no salão', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Cortinas elétricas na cabine master', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Estabilizador Seakeeper - NG9 e NG6', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Terceira estação de comando no cockpit, com cobertura', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Revestimento em teca nos passadiços e proa', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Revestimento em teca na plataforma de banho', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Lift elétrico para TV 48" no Salão', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Hard Top com lâminas de sombreamento', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Dessalinizador', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Pintura anti-fouling', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Icemaker na popa', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Icemaker no Flybridge', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'TVs + soundbar nas cabines (substitui alto falantes)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Luzes submergíveis (8)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Farol de busca elétrico', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Câmeras de monitoramento (2 internas e 1 externa)', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Tendalino de cobertura para a proa', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Mesa em teca na proa', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Revestimento em mármore nas paredes do banheiro e do box da cab. máster', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Pisos dos WC em mármore', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Lounge de popa do flybridge com móveis soltos Tidelli ou Artefacto', 'Padrão', 1, true, null),
('FY 720', 'Versão Clara com Acabamento Canettato', 'Stobag elétrico na popa', 'Padrão', 1, true, null);