-- Inserir dados FY670 (mantendo dados existentes)
INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
('FY 670', 'Plataforma Principal', 'Acesso à plataforma de popa (2) através de um degrau de fibra de vidro e portões de aço inoxidável (2)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Acesso à área da tripulação através de degraus na base da porta', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Acesso à posição do leme (porta lateral)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Acesso à casa das máquinas através de uma escotilha e uma escada de aço inoxidável e teca', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Acesso ao flybridge através de degraus de fibra de vidro, aço inoxidável e teca', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Plataforma de popa com depósitos (2), plataforma elevatória hidráulica (450kg) e escada de banho dobrável', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Porta deslizante traseira com estrutura de aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Croque', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Alça de proa em aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Púlpito de proa com grades laterais e aberturas laterais', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Bow thruster (13,4 Hp), alta eficiência', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Âncora estilo Bruce (30Kg, 75mt. corrente, 12 mm de diâmetro)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Armário de cockpit com armazenamento', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Iluminação no cockpit', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Sofá na praça de popa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Defensas cilíndricas (6)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Guincho de âncora elétrica (2000W) com controles na proa, na posição do leme principal e posição do leme do flybridge', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Alarme acústico externo para o nível da água de porão na proa e na popa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Capas de defensas com logotipo Ferretti', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Piso da proa e passadiços em fibra de vidro com superfície antiderrapante', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Chuveiro de mão com água doce quente/ frio na plataforma de popa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Paiol de âncora', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Suporte de cabos de amarração na proa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Cabos de amarração (4, 12 mt)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Estações de amarração (2) com tampas em fibra de vidro, e espaço de armazenamento para os cabos de amarração', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Alavanca na sala de máquinas (desligamento de motor e gerador, desligamento de entradas de ar (2) e ventilador, acionamento do sistema de extinção de incêndio)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Mangueira de água salgada de combate a incêndios e lavagem de corrente na proa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Pia com água salgada e água doce quente/ fria na estação de amarração', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Sofás com almofadas e armazenamento na proa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Mesa de cockpit em aço inoxidável e teca', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Cunho de amarração de aço inoxidável: na popa (2), no meio do navio (1 para cada lado) e na proa (2)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Passa cabo de popa (2) e proa (2)', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Armazenamento no banco de popa', 'Padrão', 1, true, null),
('FY 670', 'Plataforma Principal', 'Piso do cockpit e degraus para plataforma de popa de teca', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Acesso ao deck inferior (Escadaria de madeira)', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Porta de correr na popa de vidro temperado com estrutura de aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Armários com prateleiras', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Área de jantar (sofá com mesa de jantar de vidro e 2 cadeiras)', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Sistema de Home Theater Hi-Fi (2+1)', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Modem roteador de Internet Wi-Fi', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Área de estar (sofás)', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Cortina romana (simples) nas janelas laterais', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'Cortina na porta de entrada', 'Padrão', 1, true, null),
('FY 670', 'Salão', 'TV LED 32" ou equivalente', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Armários com prateleiras e gavetas', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Fogão tipo cooktop', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Louças, copos e talheres de aço inox – kit para 8 pessoas', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Exaustor sobre o cooktop', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Geladeira (198lt.) + freezer (57lt.)', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Microondas', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Armário de cozinha suspenso Janela lateral com abertura manual', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Pia de aço inoxidável com água doce quente/fria', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Cortina', 'Padrão', 1, true, null),
('FY 670', 'Cozinha', 'Bancada', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Acesso ao deck (porta lateral)', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Unidade de controle piloto automático', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Barômetro, relógio e higrômetro', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Saída de acendedor de cigarro (12V)', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Manetes eletrônicos para motores, com função easy-dock e funções auto-trolling', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Contador de corrente digital eletrônico', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Carpete', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Bateria paralela instantânea', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Sistema de monitoramento integrado (integrado com sistema de navegação)', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Bússola magnética', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Posição do leme principal com instrumentação completa', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Tela multifuncional para sistema de navegação (radar, plotter cartográfico, GPS, sonda, dados dos motores) (3)', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Radar integrado com sistema de navegação', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Apoio de pés reclinável', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Banco do piloto, com movimentação manual (2)', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Painéis elétricos secundários para corrente alternada e contínua', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Compartimento de armazenamento', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Quadro de distribuição sinóptico com alarmes', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'VHF', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Limpa pára-brisas (2) com temporizador', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Revestimento de primer sob anti-incrustante', 'Padrão', 1, true, null),
('FY 670', 'Comando Principal', 'Coberturas de proteção frontal e lateral do pára-brisas (na cor preta)', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Acesso ao cockpit através de degraus em fibra de vidro e teca e corrimão em aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Gaiúta da escada do cockpit com corrimão de aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Iluminação de cortesia', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Cobertura para a posição do leme e banco do piloto', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Armário com pia', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Arco de radar em fibra de vidro e aço inoxidável (radar suporte, antenas, sinais, bandeira)', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Coletes salva-vidas (10)', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Boia salva-vidas com cabo flutuante', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Luzes de navegação', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Defletor frontal e lateral de acrílico', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Farol de busca manual com alcance de 1/2 milha, 12V', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Sofá com espaço de armazenamento embaixo', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Guarda-corpo na popa', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Solário', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Mesa', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Antena de tv', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Buzina de alerta com compressor', 'Padrão', 1, true, null),
('FY 670', 'Flybridge', 'Alto-falantes estanques (2)', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Manetes eletrônicos para motores, com função easy-dock e funções auto-trolling', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Banco do piloto', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Mini Hi-Fi, à prova d''água', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Tela multifuncional para sistema de navegação (radar, plotter cartográfico, GPS, sondas) repetidor', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Tomada 12V', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'Segunda posição de pilotagem equipada com instrumento e alarmes', 'Padrão', 1, true, null),
('FY 670', 'Posição de Comando do Flybridge', 'VHF', 'Padrão', 1, true, null),
('FY 670', 'Hall/Corredor', 'Acesso ao deck principal (Escadaria de madeira)', 'Padrão', 1, true, null),
('FY 670', 'Hall/Corredor', 'Carpete', 'Padrão', 1, true, null),
('FY 670', 'Hall/Corredor', 'Armazenamento sob a escada', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Armários de cabeceira (2)', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Armário com gavetas', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Armários com prateleiras', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Espreguiçadeira', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Mesa com gavetas, prateleiras, cadeira', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Cama de casal com colchão, travesseiros e colcha', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Carpete', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Parede com gaveta, armário e prateleiras embutidas', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Janela do casco (2) com escotilha de aço inoxidável que pode ser aberta', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Mini Hi-Fi', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Persiana romana', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Cofre', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Cabeceira estofada', 'Padrão', 1, true, null),
('FY 670', 'Cabine Principal', 'Guarda-roupa com cabideiro, espelho e janela', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Armário com gaveta e espelho', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'WC elétrico', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Persianas', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Janela do casco com escotilha de aço inoxidável que pode ser aberta', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Armários', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Chuveiro com porta de vidro temperado, banco de madeira, escotilha de abrir de aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Bancada em Corian', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Painel de controle do WC', 'Padrão', 1, true, null),
('FY 670', 'Banheiro Master', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Cama de casal com colchão, travesseiros e colcha', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Gavetas embaixo da cama', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Escotilha de escape', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Carpete', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Janelas do casco (2) com escotilhas de aço inoxidável que podem ser abertas', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Espelho', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Persiana romana', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Prateleiras', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Cabeceira estofada', 'Padrão', 1, true, null),
('FY 670', 'Cabine VIP na Proa', 'Roupeiros (2) com espelho', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'WC elétrico', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Persianas', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Janela do casco com escotilha de aço inoxidável que pode ser aberta', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Armário', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Espelho', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Chuveiro com porta de vidro temperado', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Bancada em Corian', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Painel de controle do WC', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Cabine VIP', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Camas (2) com colchões, travesseiros e colchas', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Mesa de cabeceira com gaveta', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Gaveta embaixo da cama', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Carpete', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Janela do casco com escotilha de abrir em aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Espelho', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Luzes de leitura (2)', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Persiana romana (solteiro)', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Cabeceira estofada', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Guarda-roupa com espelho', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'WC elétrico', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Persiana', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Janela do casco com escotilha de aço inoxidável que pode ser aberta', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Armário', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Espelho', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Chuveiro com porta de vidro temperado', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Pia em Corian', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Painel de controle do WC', 'Padrão', 1, true, null),
('FY 670', 'Cabine de Hóspedes', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 670', 'Lobby da Área da Tripulação', 'Acesso ao deck principal', 'Padrão', 1, true, null),
('FY 670', 'Lobby da Área da Tripulação', 'Painel elétrico para corrente alternada e contínua', 'Padrão', 1, true, null),
('FY 670', 'Lobby da Área da Tripulação', 'Área de armazenamento', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Tripulação', 'WC com água doce', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Tripulação', 'Armários', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Tripulação', 'Espelho', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Tripulação', 'Chuveiro com cortinas impermeáveis', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Tripulação', 'Escotilha de abrir em aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Banheiro da Tripulação', 'Pia com água doce quente/fria', 'Padrão', 1, true, null),
('FY 670', 'Cabine da Tripulação', 'Cama com colchão, travesseiro e colcha', 'Padrão', 1, true, null),
('FY 670', 'Cabine da Tripulação', 'Mesa de cabeceira', 'Padrão', 1, true, null),
('FY 670', 'Cabine da Tripulação', 'Gabinete com armários', 'Padrão', 1, true, null),
('FY 670', 'Cabine da Tripulação', 'Tapete embutido', 'Padrão', 1, true, null),
('FY 670', 'Cabine da Tripulação', 'Escotilha de abrir em aço inoxidável', 'Padrão', 1, true, null),
('FY 670', 'Cabine da Tripulação', 'Guarda-roupa', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Sala de máquinas', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Acesso ao cockpit através de uma escotilha e uma escada de aço inoxidável e teca', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Entradas de ar com separador (2)', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Válvulas de mudança (2) para bombeamento de emergência de água do porão Bomba de esgoto elétrica', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Ventilador elétrico (2)', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Sistema de extinção de incêndio com controle manual/automático', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Saída de água doce para enchimento e lavagem', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Indicadores de níveis do tanque de combustível', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Gerador 120/240V 21,5kW 60Hz', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Tanque de combustível GRP (3830lt.) com tanque de decantação e descarga', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Lâmpada portátil', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Filtros de motores Racor', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Pré-filtro de combustível Racor para gerador', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Filtro de água para o sistema de refrigeração do gerador', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Filtros de água (2) para o sistema de arrefecimento do motor', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Antepara dianteira estanque', 'Padrão', 1, true, null),
('FY 670', 'Área Técnica', 'Piso de madeira com superfície antiderrapante', 'Padrão', 1, true, null),
('FY 670', 'Equipamento de Propulsão e Controle', 'Propulsão e controle', 'Padrão', 1, true, null),
('FY 670', 'Equipamento de Propulsão e Controle', 'Bow thruster (13,4 Hp)', 'Padrão', 1, true, null),
('FY 670', 'Equipamento de Propulsão e Controle', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
('FY 670', 'Equipamento de Propulsão e Controle', 'Escapes silenciados', 'Padrão', 1, true, null),
('FY 670', 'Equipamento de Propulsão e Controle', 'Caixa de contenção com vedação do eixo sem gotejamento, baixa manutenção Transmissão V-Drive', 'Padrão', 1, true, null),
('FY 670', 'Sistemas de Estabilização', 'Interceptores', 'Padrão', 1, true, null),
('FY 670', 'Comunicação', 'Roteador de modem de Internet Wi-Fi', 'Padrão', 1, true, null),
('FY 670', 'Comunicação', 'VHF (2)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Monitoramento', 'Tela de sistema de monitoramento integrado (integrado com sistema de navegação)', 'Padrão', 1, true, null),
('FY 670', 'Navegação', 'Unidade de controle do piloto automático (posição principal do leme)', 'Padrão', 1, true, null),
('FY 670', 'Navegação', 'Tela de toque multifuncional para sistema de navegação (radar, plotter cartográfico, GPS, sondas) e repetidor', 'Padrão', 1, true, null),
('FY 670', 'Navegação', 'Tela de toque multifuncional para sistema de navegação (radar, plotter cartográfico, GPS, sonda, dados dos motores) (3)', 'Padrão', 1, true, null),
('FY 670', 'Navegação', 'Radar integrado com sistema de navegação', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Extinção de Incêndio FM200', 'FIREBOY na casa de máquinas com controle automático/manual', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Extinção de Incêndio FM200', 'Extintores de incêndio portáteis', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Extinção de Incêndio FM200', 'Alavanca de emergência na sala de máquinas (desligar motor e gerador, ativação de sistema de extinção de incêndio)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Extinção de Incêndio FM200', 'Sistema de alarme de detecção de fumaça', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Carregador automático de bateria (24V) para baterias de serviço auxiliares, carga da bateria do motor reduzida', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Carregador de bateria para gerador', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Chaves de desconexão da bateria: mecânica (sala de máquinas) e eletrônica (cockpit)', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Caixa do disjuntor', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Chave Carling 100A para 240V', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Proteção catódica com ânodos de zinco', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Tomadas internas duplas de 120V em cada caixa', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Bateria de partida do gerador 24V (baixa perda de água)', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Ligação com terra para entrada de água do mar e grades', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Interruptores de falha de aterramento (soquetes)', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Grupo de baterias de serviço auxiliar de 24V', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Grupo de baterias de 24V para bow thruster', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Grupo de baterias de baixa perda de água de 24V para partida do motor', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Transformador de isolamento 25kVA', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Iluminação LED em 24V', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Chave de desconexão manual da bateria para gerador', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Instrumentos de medição', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Voltímetro', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Mecânico (cockpit) e instantâneo (posição principal do leme) chave paralela de bateria elétrica', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Predisposição para TV + sistema decodificador em todas cabines: cabo 120V + conector F + cabos de antena de TV', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Tomada de cais (63A 230V)', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Tomada de cais 100A 60Hz', 'Padrão', 1, true, null),
('FY 670', 'Sistema Elétrico', 'Interruptor de tomada de cais 100A 30mA, com proteção contra falha de aterramento', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Porão', 'Bomba de esgoto elétrica (casa de máquinas, espaço de acomodação)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Porão', 'Tubo de sucção de esgoto de emergência (sala de máquinas) através da bomba de arrefecimento do motor', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Sistema de águas negras com tanque e deck conexão para bombeamento do tanque', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Sistema de WC elétrico com água doce', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Bomba autoclave de água doce (24V) com controle eletrônico', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Tanque de água doce (1.000lt)', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Sistema de água cinza com tanque', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Entrada de água do mar independente para ar condicionado com filtro', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Captação independente de água do mar para sistema de água do mar com filtro', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Entrada independente de água do mar para dessalinizador com filtro', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Bomba de autoclave de água do mar para limpeza e combate a incêndio com mangueira na proa', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Válvula de 3 vias na cozinha', 'Padrão', 1, true, null),
('FY 670', 'Sistemas Sanitários e de Água', 'Aquecedor de água (230V, 60lt)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Sistema de ar condicionado em cabines (banheiros inclusos)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Estabilizadores Seakeeper 2x NG6', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Ar condicionado Tropical 72.000 BTU', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Gerador Onan 19kw', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Passarela de embarque com revestimento em teca', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Porta estanque para acesso a sala de máquinas pela cabine marinheiro', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Entrada para abastecimento de água doce', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Hard top em fibra de vidro', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Sistema de sombreamento com postes de carbono para dinette de proa', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Revestimento em teca na proa e nos passadiços', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Revestimento em teca na plataforma de banho', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Revestimento em teca no flybridge', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Luzes de cortesia para áreas externas', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Mesas em teca na proa, conversíveis em solário', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Mesa em teca no flybridge', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Chuveiro na popa', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Lixeira no cockpit', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Piso em madeira laminada no deck principal', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Porta copos na mesa do cockpit', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Tábua de cobertura da pia em madeira', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Degrau chanfrado no acesso do comando principal para o deck inferior', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Prateleira adicional no armário da cabine de hospedes', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Stern thruster', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Marcador de corrente', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Filtro Racor', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Sistema Xenta com DPS', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Sistema de sombreamento com postes de carbono para a popa do flybridge', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Degraus em teca nos passadiços', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Guinchos de amarração', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Triturador de resíduos na pia da cozinha', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Luzes embutidas na escada de acesso ao deck inferior', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Cofre digital', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Cabine marinheiro com cama retrátil adicional', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Monitoramento de funções do ar condicionado e gerador', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'CCTV câmera externa colorida', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Sistema central REVERSO para troca de óleo dos motores, inversores e geradores', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Pega-mão para a escada de banho (ambos os lados)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Guarda corpo abrível (ambos os bordos)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Inversor e carregador de baterias Mastervolt Mass Combi 24V 2.5 kW 60A', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Luzes de cortesia para a plataforma submergível', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Lift elétrico para a TV 43" do salão', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Joystick nas duas estações de comando -', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Estação de controle no cockpit (3o comando)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Upgrade de telas Simrad – 3x tela 16" Evo 3 no comando principal, 2x tela 12" no flybridge', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'AIS transponder Simrad NAIS500 (RX-TX)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Unidade de controle de piloto automático Simrad', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Máquina lava-roupas', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Máquina seca-roupas', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Domo vazio', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Geladeira 50l no flybridge', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Dessalinizador', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Icemaker no flybridge', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Cadeiras tipo diretor para o cockpit (2)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Luzes submergíveis (7)', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Icemaker no cockpit', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Lava-louças', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Paredes do banheiro da cabine master revestidas em calacata', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Pintura cinza no domo vazio', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Pintura cinza na antena de radar Radome', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Pintura cinza na buzina', 'Padrão', 1, true, null),
('FY 670', 'Sistema de Ar Condicionado', 'Pintura cinza na antena VHF', 'Padrão', 1, true, null);