-- Inserir itens do memorial descritivo do modelo FY850
INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
('FY850', 'CONVÉS PRINCIPAL', 'Acesso ao flybridge por escada de aço inox e degraus de teca com corrimão em aço inox', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Acesso a plataforma de popa por degraus de teca e corrimão em aço inox', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Acesso a praça de máquinas por porta a bombordo e escotilha no cockpit e escada de aço inox e degraus de teca', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Garagem de popa com iluminação', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Pega-mão de popa com cunhos (2)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Porta de correr de vidro com armação de aço inox', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Croque de amarração (2)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Passa-cabos de proa em inox (2)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Púlpito de proa com guarda-corpo', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Bow thruster (hidráulico de 30hp)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Ancoras Bruce (50Kg e 30Kg) com 2 correntes (100 m e 75 m, 12mm diâmetro)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Cadeiras no Cockpit (4)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Defensas cilíndricas (8)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Guinchos de ancora elétricos (2 x 2700 W) com controle na proa, comando principal e comando do flybridge', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Porta da Garagem eletro-hidráulica submersível com revestimento de teca na parte interna', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Alarme acústico externo para nível de água de porão localizados na proa e popa', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Capas para defensas (10) com logo Ferretti Yachts', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Guinchos de amarração com controle de pé (2x 1500 W)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Escotilhas de acesso ao bico de proa (2)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Icemaker no Cockpit', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Luzes indiretas nas laterais do convés e proa', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Iluminação no cockpit', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Iluminação nas laterais de passagem', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Living e solário na proa com sofás, paióis para armazenamento, capas e mesa', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Porta-cabos no bico de proa', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Cabos de amarração (72 m)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Postos de amarração (2) com capas de fibra e paióis para armazenamento de cabos.', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Trilho para capa de cobertura (cockpit e passagens laterais)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Tela de proteção para para-brisa e janelas laterais da casaria', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Puxadores na casa de máquinas para desligamento de motores e ativação do sistema de ex¬tinção de incêndio', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Passa-cabos com roletes, na popa (2), proa (3), mangueiras de incêndio de água salgada e lavador de âncora', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Cabo de energia de cais (230 V, 15m)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Chuveiro com água quente e fria (acesso degrau na plataforma de popa)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Porta de saída lateral (2)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Pia com água quente e fria na praça de popa', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Ferragens em aço inox', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Cunhos em aço inox: popa (4), meia-nau (2), e proa (3)', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Sofá de popa com encosto reposicionável para uso como solário', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Paiol no suporte de boreste', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Solário na proa com colchão e almofadas e paióis', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Plataforma de popa Eletro-hidráulica dobrável, com revestimento de teca', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Mesa do cockpit em teca', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Teca no piso do convés principal', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Passarela eletro-hidráulica com revestimento de teca e controle remoto (2) e hastes de guarda corpo com levantamento automático', 'Padrão', 1, true, NULL),
('FY850', 'CONVÉS PRINCIPAL', 'Caixas de som a prova d''água (2) no cockpit com amplificador e controle remoto', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Porta manual do salão deslizante em vidro temperado com estrutura em aço inox', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Ar-condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Móvel bar', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Armário com prateleiras', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Iluminação de teto de cortesia', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Resfriador de gaveta (lt75 24V)', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Sistema de som', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Área de estar (sofá, mesa de café)', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Cortinas padrão na porta traseira', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'Cortinas padrão nas janelas laterais', 'Padrão', 1, true, NULL),
('FY850', 'Salão', 'TV LED 40" ou equivalente', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Acesso à cozinha (porta de correr)', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Ar condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Estantes (2)', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Cadeiras (8), louça de mesa, copos e talheres de aço inoxidável, para 12', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Cristaleira', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Mesa de jantar', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Cortinas padrão nas janelas laterais', 'Padrão', 1, true, NULL),
('FY850', 'Área de Jantar', 'Degraus de madeira para o convés inferior', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Vaso elétrico de cerâmica com água fresca', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Exaustor', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Espelho', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Persianas', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Lavatório', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Painel de controle do vaso sanitário com indicador (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Lavabo', 'Pavimento de madeira', 'Padrão', 1, true, NULL),
('FY850', 'Área da Cozinha', 'Acesso à área de jantar (porta de correr)', 'Padrão', 1, true, NULL),
('FY850', 'Área da Cozinha', 'Painel elétrico', 'Padrão', 1, true, NULL),
('FY850', 'Área da Cozinha', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Área da Cozinha', 'Porta de saída lateral manual, porta deslizante de acesso a cozinha e degraus de madeira', 'Padrão', 1, true, NULL),
('FY850', 'Área da Cozinha', 'Degraus de madeira com corrimão de aço inoxidável na posição elevada do leme principal', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Ar condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Armário com prateleira e gavetas', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Degraus de acesso a área da tripulação', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Cooktop cerâmico', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Bancada', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Sala de jantar com assentos e mesa', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Lava-louça', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Forno combinado elétrico/ Micro-ondas', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Exaustor com tomada externa (230V)', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Geladeira (204lt) e freezer (72lt 230V, 24v através do inversor)', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Armários superiores com prateleiras', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Janelas laterais com abertura em aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Porta de correr (2) para a cozinha', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Pia de aço inoxidável com água quente/fria e piso de madeira de vinil', 'Padrão', 1, true, NULL),
('FY850', 'Cozinha/ Galley', 'Piso vinílico padrão madeira', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Ar-condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Unidade de controle piloto automático', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Barômetro, relógio e higrômetro', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Tomada (12V)', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Banco do co-piloto', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Sistema de direção eletro-hidráulico', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Manete com joystick "easy-dock" e função auto-troll', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Controle eletrônico de contagem de corrente', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Banco do piloto', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Paralelo de bateria instantâneo', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Manual digital interativo no Ipad', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Bússola magnética', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Console principal com instrumentação completa', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Sistema de monitoramento integrado com tela touch-screen', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Radar, chartplotter e GPS, sonda com display LCD colorido e profundímetro', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Indicador de ângulo de leme', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Porta de saída lateral com janela de abrir', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Painel elétrico sinóptico com alarmes acústicos e visuais', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'VHF', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Limpador de para-brisa (2) com timer', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Piso de madeira', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Degraus de madeira de acesso a área da cozinha', 'Padrão', 1, true, NULL),
('FY850', 'Comando Principal', 'Pintura com primer debaixo do anti-encrustante', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Acesso ao flybridge por escada de aço inox e degraus de teca com corrimão em aço inox', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Radar de banda larga', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Gaiuta na escadaria do cockpit', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Luzes de cortesia', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Cobertura para o console e para o banco do piloto', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Mastro de sinais de navegação diurnos', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Mastro de bandeira', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Móvel com bar completo (Refrigerador de 50lt, armário, bancada, pia)', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Targa de fibra de vidro para radar', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Coletes salva vidas (12), boia flutuante com retinida e facho Holmes', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Iluminação no flybridge', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Luzes de navegação', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Para-brisa de policarbonato e armação de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Farol de busca portátil 12 V', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Guarda-corpo', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Sofás com cobertura (3)', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Mastro de bandeiras e sinais de navegação de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Mesa', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Antena de TV', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Buzina com compressor', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Alto-falante a prova d''água (2)', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Comando do Flybridge', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Sistema de direção eletro-hidráulica', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Controle eletrônico com manete com joystick "easy-dock" e função auto-troll', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Contador eletrônico de corrente', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Banco do piloto com paiol', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Painel de instrumentos', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Sistema de som Mini Hi-Fi, a prova d''água com bluetooth', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Radar, repetidor de chartplotter com tela touch screen LCD colorida, GPS e piloto automático', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Indicador de ângulo do leme', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Segunda posição de comando equipada com instrumentos e alarmes', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'Tomada 12 V', 'Padrão', 1, true, NULL),
('FY850', 'FLYBRIDGE', 'VHF', 'Padrão', 1, true, NULL),
('FY850', 'Lobby', 'Acesso área convés Principal (escada madeira e corrimão em aço inox)', 'Padrão', 1, true, NULL),
('FY850', 'Lobby', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Ar-Condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Mesas de cabeceira (2) com gaveta', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Cofre Digital', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Cama casal com colchão, travesseiros e jogo de cama, armazenamento', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Gavetas (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Penteadeira com cômoda, prateleiras, espelho e pufe', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Janelas de casco (2) com vigias de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Iluminação indireta', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Som HI-FI CD/DVD', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Espelhos', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Ventilação natural embaixo da cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Luzes de Leitura', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Cortina romana e blackout nas janelas laterais', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'TV led 32" ou equivalente', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Cabeceira de cama acolchoada', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Master', 'Guarda-roupas com espelho no interior', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Gabinete com Gavetas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Bidé Cerâmica', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Porta de banheiro', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Vaso elétrico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Pia de vidro (2) com bancada em Corian', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Janela de casco com vigias de aço inoxidável,', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Espelhos', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Cortinas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Cortina prova d`água para janela chuveiro', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Chuveiro e assento madeira', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Piso cerâmico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Master', 'Painel de controle vaso com medidor do tanque de águas negras (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Ar-Condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Mesas de cabeceira (2) com gaveta', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Iluminação cortesia teto', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Cama casal com colchão, travesseiros e jogo de cama, armazenamento', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Gavetas', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Penteadeira com cômoda, prateleiras, espelho e cadeira', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Janela de casco com vigias de aço inoxidável (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Mini som com tomada USB', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Espelho', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Luzes de Leitura', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Cortina padrão e black out nas janelas laterais', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Predisposição para TV', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Cabeceira de cama acolchoada', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Ventilação natural embaixo da cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine VIP', 'Guarda-roupa', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Exaustor de ar', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Gabinete com Gavetas e Portas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Bidé Cerâmico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Cortinas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Vaso elétrico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Janela de casco com vigias de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Pia com bancada em Corian', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Armário superior com porta e espelho', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Chuveiro com porta de vidro, piso madeira', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Painel de controle vaso com medidor do tanque de águas negras (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro VIP', 'Piso de madeira', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Ar-Condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Mesas de cabeceira (2) com gaveta', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Iluminação cortesia teto', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Cama casal com colchão, travesseiros e jogo de cama, armazenamento', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Janela de casco com vigias de aço inoxidável (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Mini som com tomada USB', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Espelhos', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Luzes de Leitura', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Cortina romana e blackout nas janelas laterais', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Predisposição para TV', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Cabeceira de cama acolchoada', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Ventilação natural embaixo da cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Bombordo', 'Guarda-roupa', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Armário com gavetas e portas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Vaso sanitário cerâmico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Janela de casco com vigias de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Pia com bancada em Corian', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Armário superior com porta e espelho', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Cortinas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Chuveiro com porta de vidro e assento madeira', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Painel de controle vaso com medidor do tanque de águas negras (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Cabine Hóspedes', 'Piso de madeira', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Ar-Condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Camas (2) com colchão, travesseiros e jogo de cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Mesa de cabeceira com gaveta', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Iluminação cortesia teto', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Gavetas embaixo da cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Janela de casco com vigias de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Mini som com tomada USB', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Espelhos', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Luzes de Leitura', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Cortina romana e blackout nas janelas laterais', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Predisposição para TV', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Cabeceira de cama acolchoada', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Ventilação natural embaixo da cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Guarda-roupa', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Armário com gavetas e portas', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Vaso elétrico cerâmico', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Janela de casco com vigias de aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Pia com bancada em Corian', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Armário superior com porta e espelho', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Cortinas', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Chuveiro com porta de vidro, assento madeira', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Painel de controle vaso com medidor do tanque de águas negras (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Hóspedes Boreste', 'Piso de madeira', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Capitão', 'Vaso elétrico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Capitão', 'Armários com prateleiras e portas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Capitão', 'Chuveiro com porta de vidro, assento madeira', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Capitão', 'Vigia em aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Capitão', 'Lavatório', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Capitão', 'Painel de controle vaso com medidor do tanque de águas negras (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Ar-Condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Cama com colchão, travesseiros e jogo de cama', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Total equipado com carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Armários e Prateleiras', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Armário superior com porta e espelho', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Luzes de Leitura (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Vigias em aço inoxidável (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine Capitão', 'Guarda-roupas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Tripulação', 'Vaso elétrico', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Tripulação', 'Armários com prateleiras e portas', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Tripulação', 'Chuveiro com porta de vidro, assento madeira', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Tripulação', 'Vigia em aço inoxidável', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Tripulação', 'Lavatório', 'Padrão', 1, true, NULL),
('FY850', 'Banheiro Tripulação', 'Painel de controle vaso com medidor do tanque de águas negras (3/4 e cheio)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Ar-condicionado', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Beliches (2) com colchões, travesseiros e colchas', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Armários com prateleiras (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Luzes de leitura (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Vigias de aço inoxidável que podem ser abertas (2)', 'Padrão', 1, true, NULL),
('FY850', 'Cabine da tripulação a estibordo', 'Guarda-roupas', 'Padrão', 1, true, NULL),
('FY850', 'Lobby na área da tripulação', 'Acesso ao convés principal através de degraus acarpetados', 'Padrão', 1, true, NULL),
('FY850', 'Lobby na área da tripulação', 'Drenagem para lavadora e secadora', 'Padrão', 1, true, NULL),
('FY850', 'Lobby na área da tripulação', 'Máquina de secar', 'Padrão', 1, true, NULL),
('FY850', 'Lobby na área da tripulação', 'Máquina de lavar', 'Padrão', 1, true, NULL),
('FY850', 'Lobby na área da tripulação', 'Carpete', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Acessos à praça de popa (2) através de escada em aço inox e degraus em teca a bombordo', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Entrada de ar (2) com separador ar/ água', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Mudança sobre válvulas (2) para o bombeamento de água de emergência do porão', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Bomba de porão elétrica', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Ventiladores Elétricos (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'FM200 sistema de combate incêndio com controle automático e manual', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Entrada de água doce para enchimento e lavagem', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Indicador nível de combustível no tanque', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Gerador 21,5 KW', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Gerador 21,5 KW auxiliar', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Tanque de combustível em fibra de vidro, com capacidade de 6.750lt com tanque de decantação integrado e descarga', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Iluminação', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Painel elétrico principal', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Lâmpada Portátil', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Pré filtros Racor diesel (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Pré filtros Racor diesel geradores (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Filtro água (2) para sistema refrigeração motores', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Filtro água (2) para sistema refrigeração geradores', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Antepara prova de água', 'Padrão', 1, true, NULL),
('FY850', 'Sala de máquinas', 'Piso madeira anti-derrapante', 'Padrão', 1, true, NULL),
('FY850', 'Garagem', 'Escotilha submersível eletro-hidráulica com teca no lado interno', 'Padrão', 1, true, NULL),
('FY850', 'Garagem', 'Piso em fibra de vidro com superfície anti-derrapante', 'Padrão', 1, true, NULL),
('FY850', 'Garagem', 'Escotilhas de inspeção (3) para a sala de má¬quinas', 'Padrão', 1, true, NULL),
('FY850', 'Garagem', 'Iluminação', 'Padrão', 1, true, NULL),
('FY850', 'Propulsão e controle', 'Bow thruster (30hp)', 'Padrão', 1, true, NULL),
('FY850', 'Propulsão e controle', 'Direção eletro-hidráulica', 'Padrão', 1, true, NULL),
('FY850', 'Propulsão e controle', 'Tanque de combustível 6750l com tanque de decantação integrado e descarga', 'Padrão', 1, true, NULL),
('FY850', 'Propulsão e controle', 'Escapes silenciados', 'Padrão', 1, true, NULL),
('FY850', 'Propulsão e controle', 'Transmissão da linha do eixo', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Estabilização', 'Flaps', 'Padrão', 1, true, NULL),
('FY850', 'Sistema monitoramento', 'Sistema de gestão integrado com monitor touch-screen', 'Padrão', 1, true, NULL),
('FY850', 'Navegação', 'Unidade controle piloto automático (2) (comando principal)', 'Padrão', 1, true, NULL),
('FY850', 'Navegação', 'Radar, Display LCD Carta náutica touch com GPS e piloto automático (3) (flybridge)', 'Padrão', 1, true, NULL),
('FY850', 'Navegação', 'Radar, Display LCD Carta náutica touch com GPS e sonda de profundidade (3) (comando prin¬cipal)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de extinção de incêndio', 'FM200 FIREBOY sistema de combate incêndio na praça de máquinas com controle manual/ automático', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de extinção de incêndio', 'Extintores portáteis', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de extinção de incêndio', 'Shut off de emergência na sala de máquinas (desligamento do motor e do gerador, ventiladores (2) desli¬gados, ativação do sistema de extinção de incêndio)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de extinção de incêndio', 'Sistema de alarme de detecção de fumaça', 'Padrão', 1, true, NULL),
('FY850', 'Sistema ar-condicionado', 'Sistema de ar-condicionado tropical em todas as cabines (banheiros inclusos)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Carregador de bateria automático para baterias de motor 24V', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Banco de Bateria 12V auxiliar dos geradores', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Carregador de bateria para bateria de serviço auxiliar, com chave para carregar o banco do bow-thruster 24 V (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Carregador de baterias para gerador (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Chaves seccionadoras da bateria: mecânica (sala de máquinas) e eletrônica (cockpit)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Caixa de disjuntor', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Chave Carling 100 A para energia de cais', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Proteção catódica com anodos de zinco', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Tomadas 120 V duplas em cada caixa', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Gerador 21,5kW- 1 principal e 1 auxiliar', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Aterramento para válvulas de água salgada e guarda-corpos', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Tomadas GFI (Ground fault interrupters) em todos os banheiros, cozinha e casa de máquinas', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Banco de baterias 24 V para motores', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Banco de baterias 24 V para serviço', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Iluminação LED interna/externa', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Inversor de luzes LED 24 V DC/ 120 V AC para geladeira', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Inversor de luzes LED 24 V DC/ 120 V AC para serviço', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Transformador isolado 25kVA (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Iluminação 24 V', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Banco de Bateria 12V principal dos geradores', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Chaves seccionadoras manuais da bateria (2) para geradores', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Interruptor paralelo da bateria elétrica mecânica (cockpit) e instantânea (comando principal)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Preparação para decoder em todas as cabines: cabo, conectores, antena de satélite', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Preparação para TV na cabine da tripulação', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Tomada de cais 100 A 240V (2)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema Elétrico', 'Sistema de proteção GFI para energia de cais 100 A – 30mA', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de bombas de porão', 'Bombas elétricas (2) para drenagem do porão (casa de máquinas, meia nau)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de bombas de porão', 'Bombas de porão (2 na sala de máquinas, 1 meia-nau)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de bombas de porão', 'Sucção de emergência por meio da tubulação de água salgada do motor', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de bombas de porão', 'Bombas elétricas multiuso (porão, água cinza e águas negras)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Bomba elétrica para descarga de águas cinzas', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Bomba automática do tanque de águas negras', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Tanque de águas negras 330l com medidor (3/4 e cheio) e saída externa', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Conexão do vaso sanitário da tripulação com o tanque de águas negras', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Sistema elétrico de vasos sanitários', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Bomba de água doce 24 V com controle eletrônico', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Tanque de água doce (1320lt)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Válvula de três vias na cozinha', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Tanque de águas cinzas (330 l)', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Entrada de água salgada independente para ar condicionado, com filtro', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Entrada de água salgada independente para água salgada, com fltro', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Entrada de água salgada separada para dessalinizador, com filtro', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Sistema de incêndio e lavagem de âncora com água salgada', 'Padrão', 1, true, NULL),
('FY850', 'Sistema de água doce e sanitário', 'Aquecedor de água (boiler) 230 V 80', 'Padrão', 1, true, NULL);