-- Migration: Inserir itens do memorial OKEAN 57
-- Total de aproximadamente 109 itens do modelo OKEAN 57

INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
  ('OKEAN 57', 'Motorização', '(2) Volvo® Penta D8 – IPS800 Diesel (600 HP cada) com IPS, sistema de Controle Eletrônico de embarcações (EVC) e estação de comando com Joystick de manobras.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Motorização', 'Proteção ativa de corrosão (ACP) com Garmin Glass Cockpit (1) tela 16"', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Construído conforme padrão CE e tanques construídos e certificados pela norma CE.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Saídas de costado em bronze abaixo da linha de água e inox acima da linha de água.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Pinturas em poliuretano branco na sala de máquinas e área de armazenamento.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Resina Ester vinílica infundida e resistente a bolhas em todo o processo de construção.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Sistema de ligação com ânodo sacrificial na popa.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Gelcoat isoftálico branco no exterior.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Casco e super estruturas infundidas usando núcleo de PVC e laminados de fibra de vidro.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Longarinas com espuma infusionada e laminada com fibra de vidro.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Anteparas estruturais laminadas a vácuo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Abas laterais com articulação hidráulica que se transformam em varandas laterais com guarda corpo de segurança.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', '(8) cunhos retráteis com mola fabricados em aço inox.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Todos os cunhos parafusados em placas de aço dentro da laminação.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Protetor de âncora em aço inox polido.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Sistema de lançador de âncora em aço inox polido, embutido. Âncora 66 lbs antideslizante.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Lançador de âncora automático com corrente de 30m e cabo de 60m. Controle no Paiol de âncora com escotilha com água doce para lavagem e drenos.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Para-brisa baixo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Vidros fumês laminados/temperados no para-brisa e laterais.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Janelas de costado em policarbonato fumê.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Passadiços nas laterais do convés.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', '(4) Defensas cilíndricas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Assentos em forma de U com estofados.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', '(2) Porta-copos e (2) lâmpadas pop-up.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Solário na frente do para-brisa com (2) porta-copos.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', '(4) Luzes subaquáticas no espelho de popa.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Teca sintética flexteek - Convés principal e lateral, praça de popa, área de proa e Varandas - linhas pretas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Plataforma deslizante.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Casco e Convés', 'Anti incrustante Pettit.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Plataforma Hidráulica submersível com capacidade de 400kg para içamento e escada de acesso em aço inoxidável polido.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', '(1) Assento de comando (Alcor) regulável e revestido em tecido vinílico.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Ducha de água doce quente e fria na praça de popa.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Escada de acesso a sala de máquinas em aço inox.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Vedações de borracha para todas as tampas de armazenamento e portas de acesso.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Solário com tampa articulada e armazenamento por baixo com (4) porta-copos e (2) luzes pop-up.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Mesa dobrável em fibra de vidro com pedestal fixo de aço inoxidável e porta-copos.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Acesso à área de armazenamento através do hatch (tampa) sob o assento do cockpit.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Portões em aço inox na popa.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cockpit e Praça de Popa', 'Porta deslizante para acessar o deck inferior.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Pia de aço inoxidável e torneira de água doce quente/fria.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Bancada de Corian com saliência na popa.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Geladeira de gaveta - 17 galões/65 litros.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Tampas de Corian para cobrir equipamentos.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Lixeira embutida.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Armário, gaveta e porta-temperos.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Máquina de gelo - 18 kg por dia.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', 'Fogão (1) boca.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cozinha do Deck Principal', '(2) banquetas rotativas fixadas no convés.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'TV Smart de 32 polegadas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'Ar condicionado de 6.000 BTU/h com controle de temperatura.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'Cama Queen-Size com armazenamento articulado abaixo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'Mesa de cabeceira com tomada 120VAC/USB e luzes de leitura.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'LED no teto e iluminação sob a plataforma da cama.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', '(2) Armários com luz automática.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'Banheiro privativo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Cabine Master de Proa', 'Aquecedor de água elétrico capacidade 40L.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Layout 57LC - 1 Quarto + Salão Amplo + 2 Banheiros (STD)', 'TV smart de 32" no salão.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Layout 57LC - 1 Quarto + Salão Amplo + 2 Banheiros (STD)', 'Ar condicionado de 16.000 BTU/h com ciclo reverso e controle de temperatura.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Layout 57LC - 1 Quarto + Salão Amplo + 2 Banheiros (STD)', 'Tomadas 120VAC / USB.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Layout 57LC - 1 Quarto + Salão Amplo + 2 Banheiros (STD)', 'Assentos de lounge em forma de U em ambos os lados com armazenamento embaixo dos assentos.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Vaso sanitário com descarga a vácuo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Bancada em Corian, piso em teca natural e chuveiro.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Revestimento em formica branco fosco.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Porta dos armários com espelho.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Pias cerâmicas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Tanque de retenção com válvula Y e descarga ao mar.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Porta toalhas em aço inox.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Tomada 120VAC com GFCI.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Cabine de ducha com porta em plexiglass.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Chuveiro de mão (portátil).', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Exaustor.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Banheiros Master e Hóspedes', 'Persianas de privacidade.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', '(6) Bombas de porão automáticas/manuais com alarme de água alta no comando.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Flaps Zipwake® - Controle no comando.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Sistema de ventilação de ar da sala de máquinas e exaustão com (2) sopradores de 11".', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Conexão de água doce na sala de máquinas para manutenção e limpeza geral.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Sala de máquinas com isolamento acústico e térmico.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Linhas de abastecimento de combustível e óleo aprovadas pela USCG.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Separadores de combustível/água para motores e gerador.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Filtros de entrada de água (colados).', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Montagens de vibrastop para motores e gerador.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sala de Máquinas', 'Filtros de entrada de água (colados).', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Painel elétrico principal 120/240V AC, localizado na porta do convés inferior.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Buzina Elétrica 12VDC.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Sistema de monitoramento e comutação digital com switches 12VDC para aplicações principais.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Luzes de navegação aprovadas pela USCG.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Baterias de célula seca com bancos independentes de 12VDC montados em caixas ventiladas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Serviço/Auxiliar/Carregadores de bateria do motor: 100/35/20 amp.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Interruptores de bateria para bancos de baterias.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Luzes da Sala de Máquinas e receptáculo 120/240VAC com GFCI.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Gerador de 11 KW com partida remota no leme.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Tomada de cais 50 AMP 120/240V com 50 pés de cabo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Sistema Elétrico', 'Sistema de ligação elétrica em todos os cascos e isolador galvânico.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Detectores de fumaça e monóxido de carbono em áreas designadas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Cortinas para a iluminação desejada e privacidade instaladas em todas as janelas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', '(5) extintores de incêndio em áreas designadas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Kit de salvatagem básico.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Sistema automático de extintor de incêndio na sala de Máquinas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Revestimento de madeira composta com acabamento fosco.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Piso vinílico padrão nas cabines e corredor.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Diversos', 'Estação de comando pintado de gelcoat black piano.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Para Todos os Layouts', 'Rádio estéreo MS-RA770 FM/Uni-Dock – 4 zonas.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Para Todos os Layouts', 'Proa – 2 alto-falantes de 7".', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Para Todos os Layouts', 'Cockpit – 2 alto-falantes de 7".', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Para Todos os Layouts', 'Popa – 2 alto-falantes de 7".', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Kit de Eletrônicos e Equipamentos', 'Garmin (glass cockpit) tela de 16".', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Kit de Eletrônicos e Equipamentos', 'Piloto automático Volvo.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Kit de Eletrônicos e Equipamentos', 'Gyro Compass; / Bússola.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Kit de Eletrônicos e Equipamentos', 'Controle de flaps.', 'Padrão', 1, true, null),
  ('OKEAN 57', 'Kit de Eletrônicos e Equipamentos', 'Rádio VHF sem fio.', 'Padrão', 1, true, null);

-- ✅ Total de 109 itens do modelo OKEAN 57 inseridos!