-- Limpar tabela memorial_okean e inserir dados FY550
TRUNCATE TABLE memorial_okean RESTART IDENTITY CASCADE;

-- Inserir dados FY550
INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
('FY 550', 'Deck Principal', 'Acesso a plataforma de popa por degraus de fibra de vidro', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Acesso a praça de máquinas por escotilha e escada de aço inox e degraus de teca', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Acesso ao flybridge por escada de aço inox e degraus de teca com corrimão em aço inox', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Acesso a cabine do marinheiro por escada de aço inox e degraus de teca, com sanitário manual, ar condicionado, pia, espelho, cama, armário, escada de acesso, vigia, escotilha de acesso técnico para a popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Porta de correr de vidro com armação de aço inox', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Local de armazenamento na popa com cobertura', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Living Área de proa com 2 sofás', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Púlpito de proa com guarda-corpo lateral e porta', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Bow thruster (8,7 Hp) alta eficiência', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Ancora estilo Bruce (20 kg, 75 metros de corrente de 8 mm)', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Armário na praça de popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Iluminação na praça de popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Sofá na praça de popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Mesa em teca natural na praça de popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Defensas cilíndricas (6) e Defensas esféricas (2)', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Guincho de âncora elétrico (1500 W com controle na proa, no comando principal e no do flybridge)', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Capa para defensas com logo da Ferretti', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Deck de fibra de vidro com anti-derrapante', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Chuveiro de mão com água doce quente e fria na plataforma de popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Vigias para tripulação na proa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Porta-cabos na proa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Cabos de amarração (12,4 m)', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Posto de amarração (2) com armário para os cabos', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Trilho para capa de cobertura', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Tela de proteção para para-brisa e janelas laterais da casaria', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Puxadores na casa de máquinas para desligamento de motores e ativação do sistema de extinção de incêndio', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Mangueira de incêndio e lavagem da ancora de proa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Escada de aço inox para embarque pela água', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Acessórios em aço inox', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Cunhos de amarração em aço inox: (2) na popa, (2) meia nau sendo um em cada bordo e (2) na proa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Passa-cabos na proa e popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Armário a bombordo', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Armário no sofá de popa', 'Padrão', 1, true, null),
('FY 550', 'Deck Principal', 'Solário na proa com almofadas', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Porta de correr em vidro temperado com armação em aço inox', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Cortinas na porta de correr', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Armário com prateleiras', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Área de jantar a boreste (sofás e mesa de jantar, laqueada e extensível', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Sistema de som Fusion std', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Persianas romanas em tecido', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'Sofá a bombordo comparte frontal reversível em banco de piloto com mecanismo elétrico de subida e descida', 'Padrão', 1, true, null),
('FY 550', 'Salão', 'TV LED 24"', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Armário com prateleira e gavetas', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Cooktop cerâmico 4 bocas', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Conjunto de louças, copos e talheres para 6 pessoas', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Cortina em tecido na janela de popa', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Coifa 110V sobre o Cooktop', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Geladeira 130 l e freezer 90 l', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Microondas com Grill', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Armários de cozinha', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Bancada da pia em quartzo ou resina', 'Padrão', 1, true, null),
('FY 550', 'Galley', 'Pia', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Controle do Piloto automático', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Barômetro, relógio e higro-termômetro', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Acendedor de cigarro 12v', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Manete de comando dos motores', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Bússola', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Painel elétrico principal', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Instrumentação completa do posto de comando', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Instrumento de navegação multifunção', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Display touchscreen multifuncional para sistema de navegação (GPS, Chartplotter, dados de motores e da embarcação) Simrad, 2 telas de 12"', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Janela lateral com abertura manual', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Degraus de acesso ao piso inferior em madeira', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Painel elétrico com alarme', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'VHF', 'Padrão', 1, true, null),
('FY 550', 'Comando Principal', 'Limpadores de para-brisa com temporizador', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Acesso ao flybridge por escada de aço inox e degraus de teca com corrimão em aço inox', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Cobertura para o comando e o sofá', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Defletor de radar', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Mastro para sinais de navegação diurnos', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Móvel completo com armários e pia', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Suporte de fibra para radar, antenas e sinais de navegação', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Coletes Salva-vidas (8)', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Boia salva-vidas com retinida e facho Holmes', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Iluminação no Flybridge', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Luzes de navegação', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Farol de busca manual com alcance de ½ milha (12v)', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Guarda-corpo', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Banco com espaço de armazenamento abaixo, conversível em banco do piloto', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Mastro de aço inox para bandeiras', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Solario com estofamento e almofadas', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Mesa em fibra de vidro', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Antena de TV convencional', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Buzina com compressor', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', '(2) alto-falantes a prova d''água', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Posto de comando no flybridge', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Manete dos motores', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Painel de instrumentos', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Display touchscreen multifuncional de navegação repetidor (GPS / Chartplotter, dados de motor e da embarcação) Simrad, 1 tela de 12"', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Segunda estação de comando equipada com instrumentos e alarmes', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Tomada 12v', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Repetidor VHF', 'Padrão', 1, true, null),
('FY 550', 'Flybridge', 'Som Hi-FI a prova d''água', 'Padrão', 1, true, null),
('FY 550', 'Corredor', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Corredor', 'Degraus cobertos de madeira', 'Padrão', 1, true, null),
('FY 550', 'Corredor', 'Armário debaixo da escada', 'Padrão', 1, true, null),
('FY 550', 'Corredor', 'Guarda-roupas com gavetas', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Área de "dinette" (sofá de dois lugares com mesa)', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Criado mudo (2) com gaveta', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Armário com prateleiras', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Cama de casal com colchão, travesseiro e jogo de cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Penteadeira com espelho, prateleiras e puff', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', '(2) janelas laterais com persianas e vigias de aço inox', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Mini som HI-FI', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Ventilação natural debaixo da cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', '(2) Luzes de leitura', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Cabeceira de cama acolchoada', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Guarda-roupas (2, um com cabideiro, espelho)', 'Padrão', 1, true, null),
('FY 550', 'Cabine Master', 'Saída de ar-condicionado', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Vaso sanitário elétrico (água doce)', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Persianas', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Janela de casco com vigia de aço inox', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Armário com prateleiras', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Espelho', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Chuveiro com box de vidro temperado', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Pia com bancada laqueada', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Painel de controle do vaso', 'Padrão', 1, true, null),
('FY 550', 'WC Cabine Master', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Cama de casal com colchão, travesseiro e jogo de cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Gaveteiro debaixo da cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Gaiuta de escape', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', '(2) Janelas de costado com vigia de aço inox', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Espelho', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Ventilação natural debaixo da cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', '(2) Luzes de leitura', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Prateleiras', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Cabeceira de cama acolchoada', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Guarda-roupas com espelho no interior', 'Padrão', 1, true, null),
('FY 550', 'Cabine VIP', 'Saída de ar-condicionado', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Vaso sanitário cerâmico elétrico', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Persianas', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Janela de costado com vigia de aço inox', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Armário', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Espelhos', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Chuveiro com box redondo de Plexiglass', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Pia com bancada laqueada', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Painel de controle do vaso', 'Padrão', 1, true, null),
('FY 550', 'WC VIP', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', '(2) Camas de solteiro', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Gabinete com compartimento para armazenamento', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Gavetas debaixo da cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Carpete', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Janela de costado com (2) vigias de aço inox', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Espelho', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Ventilação natural debaixo da cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', '(2) Luzes de leitura', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Persiana tipo Romana', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Prateleiras', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Guarda-roupas', 'Padrão', 1, true, null),
('FY 550', 'Cabine Hóspedes', 'Saída de ar-condicionado', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Vaso sanitário cerâmico elétrico', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Persianas', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Janela de costado com vigia de aço inox', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Armário', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Espelhos', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Chuveiro com box redondo de Plexiglass', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Pia com bancada laqueada', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Painel de controle do vaso', 'Padrão', 1, true, null),
('FY 550', 'WC Hóspedes', 'Piso de madeira', 'Padrão', 1, true, null),
('FY 550', 'Área de Armazenamento de Popa', 'Acesso ao deque principal por escada de aço inox e degraus de teca', 'Padrão', 1, true, null),
('FY 550', 'Área de Armazenamento de Popa', 'Tomadas 220 V', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', 'Acesso ao deque principal por escada de aço inox e degraus de teca', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', 'Cama', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', 'Vaso sanitário manual', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', 'Espelho', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', '(2) vigias de aço inox', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', 'Guarda-roupas', 'Padrão', 1, true, null),
('FY 550', 'Cabine de Marinheiro', 'Pia com água quente e fria e chuveiro retrátil', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Acesso ao deque principal por escotilha e escada de aço inox', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', '(2) Entrada de ar', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Válvula de emergência para puxada de água do porão pelos motores', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Bomba de porão de emergência', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Ventiladores elétricos', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Sistema automático de extinção de incêndio', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Torneira de água doce', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', '(2) tanques de combustível (tot. 2500 l)', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'indicadores de nível de tanque de combustível', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Filtros Racor para motores', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Pré-filtros Racor para gerador', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Filtro de água para sistema de arrefecimento do gerador', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Filtro de água para sistema de arrefecimento dos motores', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Aquecedor de água elétrico (30 l 230 V)', 'Padrão', 1, true, null),
('FY 550', 'Casa de Máquinas', 'Antepara de casa de máquinas estanque', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Bow thruster de alta eficiência 8,7Hp', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Sistema hidráulico de direção', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Propulsão em linha de eixo (eixo- pé de galinha)', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Selo mecânico sem gotejamento e de baixa manutenção', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Mufla silenciadora de gases de exaustão abaixo do nível de água', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Sistema de estabilização', 'Padrão', 1, true, null),
('FY 550', 'Propulsão e Controle', 'Flaps de Intrusão', 'Padrão', 1, true, null),
('FY 550', 'Comunicação', 'VHF (posição no posto de comando principal)', 'Padrão', 1, true, null),
('FY 550', 'Comunicação', 'Repetidor VHF (posição no posto de comando do flybridge)', 'Padrão', 1, true, null),
('FY 550', 'Navegação', 'Unidade de Controle de Piloto Automático (comando principal)', 'Padrão', 1, true, null),
('FY 550', 'Navegação', 'Display touchscreen multifuncional para sistema de navegação (GPS, Chartplottel, dados de motores e da embarcação)', 'Padrão', 1, true, null),
('FY 550', 'Navegação', 'Display repetidor touchscreen multifuncional para sistema de navegação (GPS, Chartplottel, dados de motores e da embarcação)', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Extinção de Incêndio', 'Sistema de extinção de incêndio FM200 com controle Automático/Manual', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Extinção de Incêndio', 'Extintores portáteis', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Extinção de Incêndio', 'Puxadores na casa de máquinas para desligamento de emergência dos motores e gerador e ativação manual do sistema de extinção de incêndio', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Extinção de Incêndio', 'Sistema de detecção de fumaça', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Relê de desligamento automático da bateria do bowthruster', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Carregador automático de bateria (24V) para baterias de serviço, e carga reduzida para baterias dos motores', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Carregador de bateria para banco do gerador', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Chave de bateria motorizada na casa de máquinas com controle remoto no painel de comando', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Paralelo de baterias', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Caixa de disjuntores', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Tomada de cais 50 A para 240 V', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Isolador Galvânico 50 A', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Proteção Galvânica com anodos de zinco', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Gerador 21.5 kW', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Bateria 12v de arranque do gerador (baixa perda de água)', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Aterramento de válvulas de casco e de guarda-corpos', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Tomadas tipo GFI (diferencial residual) 120V – 6mA', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Banco de bateria de serviço, de baixa perda de água, 24V', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Banco de bateria de arranque dos motores, de baixa perda de água, 24V', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Sistema de iluminação LED 24 V (exceto Casa de Máquinas)', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Chave de bateria para banco dos geradores', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Instrumentos de medição de voltagem', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Preparação para TV e decoder em todas as cabines: cabo 120v + conectores + cabo de antenas de TV', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Interruptor GFI (Diferencial Residual) para tomada de cais', 'Padrão', 1, true, null),
('FY 550', 'Sistema Elétrico', 'Tomada de cais 50ª 120/240V', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Água de Porão', 'Bomba de porão auxiliar elétrica para praça de máquinas e espaço de acomodações', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Água de Porão', 'Bombas de porão (2) elétrica para praça de máquinas e espaço de acomodações', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Água de Porão', 'Tubulação de sucção de emergência através das bombas de água dos motores', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Sistema automático de descarga de águas cinza', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Sistema de águas negra com tanque de 120 l e conexão no deque para bombeamento externo', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Sistema de vasos sanitários elétricos com água doce', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Bomba de água doce', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Tanque de água doce (680 l)', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Válvula de três vias de águas cinzas na cozinha', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Sistema de águas cinzas com tanque', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Entrada de água salgada independente para ar condicionado, com filtro', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Entrada de água salgada independente para sistema de água salgada, com filtro', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Entrada de água salgada independente para dessanilizador, com filtro', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Preparação para dessanilizador', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Bomba de água salgada', 'Padrão', 1, true, null),
('FY 550', 'Sistema Sanitário e de Água Doce', 'Aquecedor de água (230 V, 30 l)', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Sistema tropical de ar-condicionado nas cabines (banheiros inclusos)', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', '3º comando;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', '07 (sete) luzes submersas;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Upgrade de telas Simrad: 2 telas 12" EVO3 no comando principal + 1 tela de 12" EVO3 no comando do flybridge', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Bimini top com iluminação (cor cinza);', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Plataforma submergível deslizante, com revestimento em teca;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Piso vinílico no deck principal (salão, cozinha e comando principal)', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Estabilizador seekeeper NG 6;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Passarela de embarque telescópica;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Espaço Gourmet na popa, com churrasqueira e pia;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'TV 43" no salão, com lift elétrico', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'TV 32" na cabine master;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'TV 32" na cabine VIP;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'TV 22" na cabine hóspedes;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Revestimento em Calacata na parede do box do banheiro da cabine master;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Revestimento em Calacata na parede do box do banheiro da cabine hóspedes;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Revestimento em Calacata na parede do box do banheiro da cabine VIP;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Mesa em fibra de vidro no flybridge;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Luminárias (2) pop-up na proa;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Cadeiras dobráveis para o cockpit (2);', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Pintura anti-fouling;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Porta-copos em teca na proa;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Geleira no flybridge;', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Antena de internet', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Antena de TV via satélite, com domo', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Domo vazio para simetria', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Fechamento de popa (cor cinza)', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Fechamento de flybridge (cor cinza)', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Máquina lava-seca na cabine marinheiro', 'Padrão', 1, true, null),
('FY 550', 'Sistema de Ar-condicionado', 'Freezer extra na cabine marinheiro', 'Padrão', 1, true, null);