-- Inserir itens do memorial descritivo do modelo OKEAN 52
INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
('OKEAN 52', 'Motorização', '(2) Cummins QSC 8.3 (com potência de 600 HP cada), com caixa de câmbio ZF (fornecedora) e propulsão V-drive.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Motorização', '(2) Estações de Comando com Joystick e siste­ma de manobra do propulsor de proa (bow thrus­ter)', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Construído com os padrões CE.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Saídas de costado em bronze abaixo da linha de água e inox acima da linha de água.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Pinturas em poliuretano branco na sala de má­quinas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Resina Ester vinílica infundida e resistente a bo­lhas em todo o processo de construção.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Sistema de ligação com ânodo sacrificial na popa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Gelcoat isoftálico branco no exterior.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Casco e super estruturas infundidas usando núcleo de PVC e laminados de fibra de vidro.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Longarinas com espuma infusionada e laminada com fibra de vidro.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Anteparas estruturais laminadas a vácuo.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Abas laterais com articulação hidráulica que se transformam em varandas laterais com guarda corpo de segurança.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', '(8) cunhos de proa e popa fabricados em aço inox.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Todos os cunhos parafusados em placas de aço dentro da laminação.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Protetor de ancora em aço inox polido.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Sistema de lançador de âncora em aço inox poli­do, embutido. Âncora 66 lbs anti-giro.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Lançador de âncora automático com corrente de 30m e cabo de 60m. Controle no painel de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Paiol de âncora com escotilha com água doce para lavagem e drenos.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Vidros fumês laminados / temperados na lateral do casco, no para-brisa, portas e janelas da casa­ria.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', 'Passadiços nas laterais do convés.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Casco e Convés', '(4) Defensas cilindricas e (6) cabos de amarra­ção.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Proa', 'Assentos em forma de U e estofados.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Proa', 'Mesa de proa em fibra de vidro com pedestal fixo.• (2) Porta-copos.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Proa', 'Sistema de lavagem com água doce.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Plataforma deslizante submersível com capaci­dade hidráulica de 400kg / 880lbs e escada de embarque em aço inoxidável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Acesso à Sala de Máquinas com escada em aço inoxidável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Juntas/vedações de borracha para todas as tampas de armazenamento e portas de acesso.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Escada flutuante em aço inoxidável para o Flybridge com degraus revestidos em teca natural.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Iluminação embutida abaixo da extensão do Flybridge.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Degraus de plataforma Flexiteek®.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Portas deslizantes, dobráveis e portões de popa em aço inoxidável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cockpit e Praça de Popa', 'Espaço de armazenamento.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Área Gourmet de Popa', 'Pia de fibra de vidro e torneira de água doce.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Área Gourmet de Popa', 'Bancada em Corian e tábua de corte em teca natural.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Área Gourmet de Popa', 'Churrasqueira elétrica com sensor de desligamento.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Área Gourmet de Popa', 'Tampa de fibra de vidro articulada.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Bimini de cobertura com lâmpadas em LED.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Corrimãos de segurança de aço inoxidável nas escadas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Assento de comando ajustável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Console de Comando com instrumentação com­pleta do motor e equipamentos de navegação.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Todos os assentos acolchoados e com armazena­mento abaixo.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Solário a proa com colchões.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Gaiuta articulada para cobrir escadas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Para-brisa venturi emoldurado em policarbonato e alumínio.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Flybridge', 'Porta USB e porta copos na estação de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Cozinha em formato de U com bancada em Co­rian.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Janela corrediça com moldura de aço inoxidável que abre para o passadiço.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Bancada de fibra dobrável sob a janela da cozinha ao bordo BB.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Piso da cozinha e salão em vinil laminado.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Torneira de água quente-fria de aço inoxidável e pia de aço inoxidável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Luzes LED suspensas no teto.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Microondas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', '(1) Refrigerador - 130L e (1) freezer – 90L cada sob o balcão.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Geladeira de gaveta – 37L.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Armário de armazenagem e gavetas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Cooktop de Indução 2 bocas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cozinha do Salão', 'Máquina de Gelo 12VDC -18 kg/dia.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', '48k BTU/h Ar-condicionado - 3 unidades com ciclo reverso de calor.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Janelas do salão com vidro temperado sem mol­dura, duas luminárias suspensas skylights e com janelas com abertura corrediça à frente no salão.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Smart TV LED de 49" montada em elevador hi-lo em armário com espaço adicional.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'persianas retráteis em todas as janelas do salão', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Mesa dobrável em teca natural com pedestal fixo.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Armário com tampo de couro.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Luzes LED suspensas no teto.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Assentos de lounge em formato de L com gavetas por baixo.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Estação de comando inferior com painel de in­terruptores AC/DC, instrumentação completa do motor e eletrônicos.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Salão', 'Assento de comando ajustável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Smart TV de 32"', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Ar-condicionado de 10k BTU/h com ciclo reverso de calor e controle de temperatura.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Cama Queen-size com armazenamento articulado abaixo.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Colchão de espuma.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Mesa de cabeceira com entrada 120VAC/USB e luzes de leitura.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Guarda-roupa suspenso com luzes automáticas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Penteadeira/Mesa com gaveta, prateleiras e en­trada 120VAC/USB.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Janelas de casco com cortinas de privacidade e vigias de abertura para ventilação cruzada.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Master (Full Beam)', 'Aquecedor de água elétrico (sob a cama master)', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Smart TV de 32"', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Ar condicionado de 10k BTU/h – Ciclo reverso de calor e controle de temperatura.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Cama Queen-size com corredor ao redor, armaze­namento articulado abaixo e colchão de espuma.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Colchão de Espuma.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Gaiuta de proa com persiana.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Acesso privado ao banheiro.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Mesa de cabeceira com entrada 120VAC/USB e luzes de leitura.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Grande guarda-roupa suspenso com luzes auto­máticas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine VIP (Proa)', 'Janela de casco com película escura e aberturas de vigia para ventilação.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Hóspedes', 'Smart TV de 32"', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Hóspedes', 'Ar-condicionado de 6k BTU/h de ciclo reverso de calor e controle de temperatura.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Hóspedes', 'Cama de casal com beliche suspenso e colchão de espuma.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Hóspedes', 'Gabinete de armazenagem abaixo do beliche.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Hóspedes', 'Janela de casco com película escura e aberturas de vigia para ventilação.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Cabine Hóspedes', 'Tomadas 120VCA / USB na mesa de cabeceira.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Descarga a vácuo no vaso sanitário.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Área seca com bancada em corian e piso em teca natural área molhada com piso em corian e aparador em teca natural.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Paredes revestidas com madeiras laminadas e fórmica branca.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Portas de armários com espelhos e armazena­mento.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Pia cerâmica.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Banheiros: Tanque de armazenamento de 110L com válvula em Y e descarga para fora.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Portas toalhas em Aço Inoxidável.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Tomadas 120VAC com GFCI. Cabine de ducha com porta de acrílico.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Chuveiro embutido no teto e chuveiro portátil.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Exaustor.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Persianas de alumínio nos vidros para privacidade.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Banheiros Master e Hóspedes', 'Vigias de abertura para ventilação.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', '(5) Bomba automática/manual de porão com alar­me de nível alto.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Interceptor Zipwake – com controles em cada estação de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Sistema de admissão e exaustão de ar na sala de máquinas com (2) exaustores de 11 polegadas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Conexão de água doce na sala de máquinas para manutenção geral e limpeza.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Sala de máquinas com isolamento acústico e tér­mico.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Estabilizador Seakeeper NG6.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Linhas de abastecimento de combustível e óleo aprovadas pelo USCG.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Sistema automático de extinção de incêndio.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Separadores de combustível/água para motores e gerador.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Filtros de entrada de água bruta. Ligados.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Coxins para motores e gerador.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Sistema de bomba de água doce.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sala de Máquinas', 'Tanques de combustível de alumínio com válvulas de cruzamento e medidores laterais', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Buzina Elétrica 12VDC.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Fornecimento de energia 120/240VAC com dis­juntores na estação de comando inferior.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Bow thruster com controles em ambas as esta­ções de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Luzes de navegação internacionais aprovadas pela USCG.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Baterias de célula seca com bancos independen­tes de 12VDC montadas em caixas ventiladas na sala de máquinas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Baterias de célula seca separadas em caixa para bow thruster e guincho na área de proa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Carregadores de bateria de serviço / auxiliar / mo­tor: 100 / 35 / 20 amperes.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Interruptores de bateria para bancos de bateria.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Luzes da sala de máquinas e tomada 120/240VAC com GFCI.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Gerador de 16 kW com partida remota na estação de comando inferior.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Alimentação de cais 50A 120/240V com cabo de cais de 50''.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Sistema Elétrico', 'Sistema de ligação elétrica e isolador galvânico.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Detector de monóxido de carbono/fumaça em áreas designadas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', '(5) Extintores de incêndio em áreas designadas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Pacote de segurança básico.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Móveis com madeira folheada composta', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Piso em vinil laminado em todos os quartos e cor­redores.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Estofamento externo em tecido vinilico Spradling - Silvertex', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Painel de comando principal em gelcoat preto e painel de comando secundário em gelcoat branco.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Pacote de Som - Fusion', 'Fusion Dual Zone Marine Stereo .', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Pacote de Som - Fusion', 'Salão – 2 Auto falantes de 6,5".', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Pacote de Som - Fusion', 'Popa – 4 Auto falantes de 7" e 1 subwoofer de 10".', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Pacote de Som - Fusion', 'Flybridge – 2 Auto falantes de 7".', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Pacote de Som - Fusion', 'Proa – 2 Auto falantes de 7".', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando Principal', 'Simrad (1) display de 12"', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando Principal', 'Bússola giroscópica.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando Principal', 'Controles de trim por Interceptor Zipwake.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando Principal', 'Rádio VHF', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando do Flybridge', 'Simrad (1) display de 9" motores Cummins.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando do Flybridge', 'Bússola giroscópica.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando do Flybridge', 'Controles de trim por Interceptor Zipwake.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Comando do Flybridge', 'Rádio VHF.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Piloto automático Simrad para Cummins QSC 8.3.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Propulsor de popa (Stern thruster) com controles em ambas as estações de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Estação de atracação na popa com terceiro controle para pro­pulsor de proa e propulsor de popa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Adicional de (1) display de 12" comando principal e adicional de (1) display de 9" Simrad comando secundário. Volvo', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Volvo D8-IPS 800 (600 HP) e sistema GARMIN (Glass Cockpit) com display 12" no comando principal e display de 10" no comando secundário.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Propulsor de proa com controles em ambas as estações de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Estação de atracação na popa com terceiro controle para pro­pulsor de proa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Sistema de Posicionamento Dinâmico (DPS).', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Adicional de (1) display de 12" comando principal e adicional de (1) display de 10" Glass Cockpit comando secundário.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Propulsão e Navegação', 'Painel de Controle do Piloto Automático (Glass Cockpit).', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Hard Top, resina de fibra de vidro infundida com pintura em gelcoat preto e iluminação em LED.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Mastro de radar para antenas e luzes de navega­ção.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Toldo de proa com postes em aço inoxidá­vel.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Estofamento externo com Silvertex® Diamond Print.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Mesa de proa em teca com pedestal fixo.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Pedestal para mesa de proa com coluna em elevação por acionamento elétrico .', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Suporte para tender e jetski.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Segundo assento no flybridge (Alcor ou Llebroc).', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', '(2) Luzes retráteis (POP-UP) ao lado da churras­queira.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', '(2) Luzes retráteis (POP-UP) solário de proa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Flexiteek - Cor Teca Natural com Linhas Cinzas.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Toldo retrátil elétrico na praça de popa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Características Externas', 'Verdugo com perfil de borracha e acabamento em inox para proteção do costado.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Dessalinizador de 130 L/H.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Ar-condicionado de 6k BTU/h para espaço de armazenamento.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Cabine para marinheiro (Exclusão do espaço para armazenamento).', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Tomada de cais com enrolador de cabos.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Adega refrigerada para 8 garrafas na suíte princi­pal.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Adega refrigerada para 8 garrafas na cozinha. . Cooktop 01 boca na área gourmet de popa', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Conforto e Entretenimento', 'Carpete no convés inferior - Seleção de cor. Máquina lava-seca (combo) – capacidade 11kg', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Farol de busca com controles em ambas as esta­ções', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Capas de lona para todos os assentos exteriores e área de comando.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Luzes subaquáticas adicionais (Kits com 02 unidades).', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Contadores de corrente nos painéis de comando principal e secundário.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Cofre na cabine master.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Defensas adicionais (Kits com 02 unidades).', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Kit de salvatagem completa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Fechamento em tecido acrílico na praça de popa.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Fechamento em tecido acrílico no flybridge.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Capa total para proteção da embarcação.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Pintura propspeed.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Pintura de fundo anti-incrustrante International Pintura de fundo anti-incrustrante Coppercoat.', 'Padrão', 1, true, NULL),
('OKEAN 52', 'Diversos', 'Pintura linha de beleza.', 'Padrão', 1, true, NULL);