-- Limpar tabela memorial_okean
TRUNCATE TABLE memorial_okean;

-- Popular memorial_okean com dados do CSV
INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item) VALUES
('FY 550', 'ESTRUTURA E CASCO', 'Casco em fibra com resina poliéster isoftálica tipo Aeroeste Crystal Reichold', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Coberta e superstrutura em fibra de vidro', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Defensas laterais e frontais em fibra', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Plataforma de popa em fibra', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Painéis divisórios dos compartimentos em MDF naval 18mm e 15mm', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Piso dos compartimentos em MDF naval 18mm', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Forro dos compartimentos em MDF naval 3mm', 'Padrão'),
('FY 550', 'ESTRUTURA E CASCO', 'Forro do teto em MDF naval 3mm', 'Padrão'),
('FY 550', 'PINTURA', 'Fundo em epóxi', 'Padrão'),
('FY 550', 'PINTURA', 'Acabamento externo em poliuretano branco com faixa decorativa na cor azul', 'Padrão'),
('FY 550', 'PINTURA', 'Acabamento interno em esmalte sintético branco', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Deck antiderrapante em fibra texturizada', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Cockpit com piso antiderrapante em fibra texturizada', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Guarda-mancebos em aço inox 316L', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Corrimãos laterais em aço inox 316L', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Escada de acesso ao flybridge em aço inox 316L', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Âncora em aço galvanizado 20 kg com 30 metros de corrente 8mm', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Cabrestante elétrico para âncora', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Escotilha de acesso ao porão de proa', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Porta lateral de acesso em aço inox', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Mesa de popa em fibra', 'Padrão'),
('FY 550', 'DECK E COCKPIT', 'Solário de popa com estofamento em courvin náutico', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Console de comando em fibra', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Assento do piloto em fibra com estofamento em courvin náutico', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Banco de passageiros em fibra com estofamento em courvin náutico', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Mesa em fibra', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Solário de proa com estofamento em courvin náutico', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Toldo retrátil', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Guarda-mancebos em aço inox 316L', 'Padrão'),
('FY 550', 'FLYBRIDGE', 'Escada de acesso ao solário de proa', 'Padrão'),
('FY 550', 'SALÃO', 'Sofá em L com estofamento em courvin náutico', 'Padrão'),
('FY 550', 'SALÃO', 'Mesa de centro em MDF com acabamento em fórmica', 'Padrão'),
('FY 550', 'SALÃO', 'Armário sob a escada', 'Padrão'),
('FY 550', 'SALÃO', 'Janelas panorâmicas com vidro temperado', 'Padrão'),
('FY 550', 'SALÃO', 'Porta de acesso ao cockpit em vidro temperado', 'Padrão'),
('FY 550', 'SALÃO', 'Piso em laminado náutico', 'Padrão'),
('FY 550', 'SALÃO', 'Forro em MDF naval 3mm com acabamento em pintura', 'Padrão'),
('FY 550', 'SALÃO', 'Iluminação em LED', 'Padrão'),
('FY 550', 'COZINHA', 'Bancada em granito', 'Padrão'),
('FY 550', 'COZINHA', 'Pia em aço inox com misturador monocomando', 'Padrão'),
('FY 550', 'COZINHA', 'Fogão cooktop 2 bocas a gás', 'Padrão'),
('FY 550', 'COZINHA', 'Geladeira 12V 110 litros', 'Padrão'),
('FY 550', 'COZINHA', 'Microondas 110V', 'Padrão'),
('FY 550', 'COZINHA', 'Armários superiores e inferiores em MDF naval', 'Padrão'),
('FY 550', 'COZINHA', 'Gavetas em MDF naval', 'Padrão'),
('FY 550', 'COZINHA', 'Iluminação em LED', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Cama de casal king size', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Colchão em espuma D33', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Armário embutido em MDF naval', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Criado-mudo em MDF naval', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Escotilha com abertura', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Janela lateral em acrílico', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Piso em laminado náutico', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Iluminação em LED', 'Padrão'),
('FY 550', 'CABINE MASTER', 'Ar condicionado split 9.000 BTUs', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Duas camas de solteiro', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Colchões em espuma D33', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Armário embutido em MDF naval', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Escotilha com abertura', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Janela lateral em acrílico', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Piso em laminado náutico', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Iluminação em LED', 'Padrão'),
('FY 550', 'CABINE HÓSPEDES', 'Ar condicionado split 9.000 BTUs', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Vaso sanitário marítimo elétrico', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Pia em aço inox com misturador monocomando', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Box com chuveiro', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Espelho', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Armário em MDF naval', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Piso antiderrapante', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Iluminação em LED', 'Padrão'),
('FY 550', 'BANHEIRO MASTER', 'Exaustor', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Vaso sanitário marítimo elétrico', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Pia em aço inox com misturador monocomando', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Box com chuveiro', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Espelho', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Armário em MDF naval', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Piso antiderrapante', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Iluminação em LED', 'Padrão'),
('FY 550', 'BANHEIRO SOCIAL', 'Exaustor', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Dois motores diesel MWM 6.12 TCE 430 HP cada', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Caixa de redução ZF 280A', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Hélices em bronze de 4 pás', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Eixo em aço inox 316L', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Gerador diesel Yanmar 13.5 kVA', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Sistema de refrigeração em circuito fechado', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Tanque de combustível em polietileno 1.000 litros', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Tanque de água em polietileno 500 litros', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Tanque de água servida 200 litros', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Sistema de combate a incêndio com extintor CO2', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Bomba de porão automática 1.100 GPH', 'Padrão'),
('FY 550', 'CASA DE MÁQUINAS', 'Isolamento termo-acústico em lã de rocha', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Quadro elétrico principal AC/DC', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Banco de baterias 12V 220Ah', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Carregador de baterias 12V 60A', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Inversor 12V/110V 3.000W', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Tomadas 110V em todos os compartimentos', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Tomadas USB em cabines', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Iluminação LED em todos os compartimentos', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Luzes de navegação', 'Padrão'),
('FY 550', 'SISTEMA ELÉTRICO', 'Holofote de busca', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'GPS chartplotter Garmin 12"', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'VHF Garmin', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'Sonda Garmin', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'Piloto automático Garmin', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'Rádio Bluetooth com alto-falantes', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'TV 32" no salão', 'Padrão'),
('FY 550', 'ELETRÔNICA', 'TV 24" na cabine master', 'Padrão'),
('FY 550', 'SISTEMA HIDRÁULICO', 'Bomba de água doce 12V pressurizada', 'Padrão'),
('FY 550', 'SISTEMA HIDRÁULICO', 'Bomba de água salgada para lavagem', 'Padrão'),
('FY 550', 'SISTEMA HIDRÁULICO', 'Aquecedor de água 40 litros', 'Padrão'),
('FY 550', 'SISTEMA HIDRÁULICO', 'Válvulas de fundo em bronze', 'Padrão'),
('FY 550', 'SISTEMA HIDRÁULICO', 'Mangueiras e conexões certificadas', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Kit de segurança completo', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Bote inflável 2.7m com motor 15HP', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Defensa e cabos de amarração', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Escada de banho em aço inox', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Chuveiro externo de água doce e salgada', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Suporte para varas de pesca', 'Padrão'),
('FY 550', 'ACESSÓRIOS', 'Churrasqueira a gás', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Casco em fibra com resina poliéster isoftálica', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Coberta e superstrutura em fibra de vidro', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Defensas laterais e frontais em fibra', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Plataforma de popa hidráulica', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Painéis divisórios em MDF naval 18mm', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Piso em MDF naval 18mm', 'Padrão'),
('FY 850', 'ESTRUTURA E CASCO', 'Forro em MDF naval 3mm', 'Padrão'),
('FY 850', 'PINTURA', 'Fundo em epóxi bi-componente', 'Padrão'),
('FY 850', 'PINTURA', 'Acabamento externo em poliuretano branco', 'Padrão'),
('FY 850', 'PINTURA', 'Faixa decorativa personalizada', 'Padrão'),
('FY 850', 'PINTURA', 'Acabamento interno em esmalte sintético', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Deck em teca sintética antiderrapante', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Cockpit com piso em teca sintética', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Guarda-mancebos em aço inox 316L', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Corrimãos laterais em aço inox 316L', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Escada de acesso ao flybridge em aço inox', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Âncora 30kg com 50m de corrente 10mm', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Cabrestante elétrico para âncora', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Escotilha de acesso ao porão', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Porta lateral elétrica em aço inox', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Mesa extensível de popa', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Sofá em L com estofamento premium', 'Padrão'),
('FY 850', 'DECK E COCKPIT', 'Solário de popa conversível', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Console duplo em fibra', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Assento do piloto ergonômico', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Banco em U com estofamento', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Mesa com refrigerador embutido', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Solário de proa XXL', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Toldo elétrico retrátil', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Bimini rígido com painéis solares', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Churrasqueira embutida a gás', 'Padrão'),
('FY 850', 'FLYBRIDGE', 'Pia molhada em inox', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Sofá em L de 8 lugares', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Mesa de jantar para 8 pessoas', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Aparador em laca brilho', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Janelas panorâmicas de vidro duplo', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Porta de correr elétrica', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Piso em porcelanato madeirado', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Forro rebaixado com iluminação indireta', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'Sistema de som Fusion', 'Padrão'),
('FY 850', 'SALÃO PRINCIPAL', 'TV retrátil 55"', 'Padrão'),
('FY 850', 'COZINHA', 'Bancada em quartzo', 'Padrão'),
('FY 850', 'COZINHA', 'Pia dupla em inox com misturador', 'Padrão'),
('FY 850', 'COZINHA', 'Fogão cooktop indução 4 bocas', 'Padrão'),
('FY 850', 'COZINHA', 'Forno elétrico embutido', 'Padrão'),
('FY 850', 'COZINHA', 'Micro-ondas de gaveta', 'Padrão'),
('FY 850', 'COZINHA', 'Geladeira frost-free 400L', 'Padrão'),
('FY 850', 'COZINHA', 'Lava-louças 8 serviços', 'Padrão'),
('FY 850', 'COZINHA', 'Adega climatizada 24 garrafas', 'Padrão'),
('FY 850', 'COZINHA', 'Armários planejados com soft-close', 'Padrão'),
('FY 850', 'COZINHA', 'Iluminação LED regulável', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Cama king panorâmica', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Colchão Castor náutico', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Closet walk-in', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Penteadeira com iluminação', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Janelas panorâmicas laterais', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Escotilhas com abertura elétrica', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Piso em porcelanato', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Ar condicionado inverter 18.000 BTUs', 'Padrão'),
('FY 850', 'CABINE MASTER', 'TV 43" motorizada', 'Padrão'),
('FY 850', 'CABINE MASTER', 'Sistema de som individual', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Cama queen central', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Colchão Castor náutico', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Armário embutido grande', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Criados-mudo duplos', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Escotilha panorâmica', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Janelas laterais grandes', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Piso em porcelanato', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'Ar condicionado inverter 12.000 BTUs', 'Padrão'),
('FY 850', 'CABINE VIP PROA', 'TV 32"', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Duas camas de solteiro conversíveis', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Colchões Castor náuticos', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Armário embutido', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Escotilha com abertura', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Janela lateral', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Piso em laminado náutico', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BB', 'Ar condicionado 9.000 BTUs', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Duas camas de solteiro conversíveis', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Colchões Castor náuticos', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Armário embutido', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Escotilha com abertura', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Janela lateral', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Piso em laminado náutico', 'Padrão'),
('FY 850', 'CABINE HÓSPEDES BE', 'Ar condicionado 9.000 BTUs', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Vaso sanitário elétrico Tecma', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Bidê elétrico', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Bancada dupla em quartzo', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Duas cubas de apoio', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Box walk-in com chuveiro de teto', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Banheira de hidromassagem', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Espelho com iluminação LED', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Armários planejados', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Piso aquecido', 'Padrão'),
('FY 850', 'BANHEIRO MASTER', 'Exaustor silencioso', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Vaso sanitário elétrico Tecma', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Bancada em quartzo', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Cuba de apoio', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Box com chuveiro de teto', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Espelho com iluminação', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Armário planejado', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Piso aquecido', 'Padrão'),
('FY 850', 'BANHEIRO VIP', 'Exaustor', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Vaso sanitário elétrico', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Bancada em granito', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Cuba de embutir', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Box com chuveiro', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Espelho', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Armário', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Piso antiderrapante', 'Padrão'),
('FY 850', 'BANHEIRO HÓSPEDES', 'Exaustor', 'Padrão'),
('FY 850', 'LAVABO', 'Vaso sanitário elétrico', 'Padrão'),
('FY 850', 'LAVABO', 'Bancada em granito', 'Padrão'),
('FY 850', 'LAVABO', 'Cuba de apoio', 'Padrão'),
('FY 850', 'LAVABO', 'Espelho decorativo', 'Padrão'),
('FY 850', 'LAVABO', 'Iluminação de destaque', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Dois motores Volvo Penta D13 900HP cada', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Caixa de redução IPS 1200', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Sistema de propulsão IPS', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Joystick de manobra', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Gerador diesel Onan 27 kVA', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Sistema de refrigeração marítimo', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Tanque de combustível 3.000 litros', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Tanque de água 1.200 litros', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Tanque de água servida 400 litros', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Sistema de combate a incêndio FM200', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Duas bombas de porão 2.200 GPH', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Isolamento acústico profissional', 'Padrão'),
('FY 850', 'CASA DE MÁQUINAS', 'Monitoramento remoto de máquinas', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Quadro elétrico digital centralizado', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Banco de baterias 24V 440Ah', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Carregador inteligente 24V 120A', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Inversor senoidal 24V/220V 6.000W', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Shore power 220V 100A', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Tomadas 220V em todos os ambientes', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Tomadas USB-C em cabines', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Iluminação LED regulável em todos os ambientes', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Luzes de navegação LED', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Holofote de busca LED 100W', 'Padrão'),
('FY 850', 'SISTEMA ELÉTRICO', 'Painéis solares 800W', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'GPS chartplotter Garmin 16" touchscreen', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Radar Garmin 72nm', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'VHF Garmin com DSC', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Sonda Garmin transducer duplo', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Piloto automático Garmin', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'AIS transceptor', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Câmeras de manobra 360°', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Sistema de som Fusion Apollo', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Alto-falantes marinizados em todos os ambientes', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Subwoofer amplificado', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'TV 65" no salão', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'TV 43" na master', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'TV 32" na VIP', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Sistema CFTV com 8 câmeras', 'Padrão'),
('FY 850', 'ELETRÔNICA', 'Wi-Fi marítimo 4G', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Bomba de água doce 24V pressurizada', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Bomba de água salgada para lavagem', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Aquecedor de água 80 litros', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Sistema de osmose reversa 100L/h', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Válvulas de fundo em bronze certificadas', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Mangueiras Trident certificadas', 'Padrão'),
('FY 850', 'SISTEMA HIDRÁULICO', 'Sistema de águas cinzas separado', 'Padrão'),
('FY 850', 'CLIMATIZAÇÃO', 'Ar condicionado central 60.000 BTUs', 'Padrão'),
('FY 850', 'CLIMATIZAÇÃO', 'Split individuais em todas as cabines', 'Padrão'),
('FY 850', 'CLIMATIZAÇÃO', 'Controle digital por ambiente', 'Padrão'),
('FY 850', 'CLIMATIZAÇÃO', 'Sistema de ventilação forçada', 'Padrão'),
('FY 850', 'CLIMATIZAÇÃO', 'Desumidificadores automáticos', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Kit de segurança Classe A completo', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Bote semirrígido 4.2m com motor 40HP', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Jet ski Sea-Doo com berço', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Guincho hidráulico para bote 500kg', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Defensas Polyform A5 (8 unidades)', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Cabos de amarração 20mm (6 unidades)', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Escada de banho elétrica retrátil', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Plataforma de mergulho hidráulica', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Chuveiros externos água doce e salgada', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Torre de pesca em alumínio', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Suporte para 6 varas de pesca', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Tanque de iscas vivas 100L', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Churrasqueira a gás premium', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Ice maker 50kg/dia', 'Padrão'),
('FY 850', 'ACESSÓRIOS', 'Cooler de convés 150L', 'Padrão'),
('FY 850', 'DOCUMENTAÇÃO', 'Documentação completa da embarcação', 'Padrão'),
('FY 850', 'DOCUMENTAÇÃO', 'Manual do proprietário', 'Padrão'),
('FY 850', 'DOCUMENTAÇÃO', 'Certificado de navegabilidade', 'Padrão'),
('FY 850', 'DOCUMENTAÇÃO', 'Garantia de 2 anos de casco e estrutura', 'Padrão'),
('FY 850', 'DOCUMENTAÇÃO', 'Garantia de 1 ano de equipamentos', 'Padrão');