-- Migration: Inserir itens do memorial FY1000
-- Total de aproximadamente 335 itens do modelo FY1000

INSERT INTO memorial_okean (modelo, categoria, descricao_item, tipo_item, quantidade, is_customizable, marca) VALUES
  ('FY1000', 'Deck Principal', 'Acesso à garagem através de escadas dobráveis', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Acessos (2) à plataforma de popa através escada de fibra, revestidas em teca e portões de aço inoxidável e vidro (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Telas de proteção pretas para as janelas frontais e laterais do posto de comando principal', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Croque de amarração (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', '(6) Defensas cilíndricas e (6) defensas esféricas', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Guinchos elétricos para âncora (2 x 3000W) com controles na proa, comando principal e Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Porta de garagem eletro-hidráulica', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Alarme acústico externo para nível de água de porão na proa e na sala de máquinas', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Capas para defensas (12) com logotipo da Ferretti Yachts', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Guinchos (2 x 2300W) nas estações de atracação', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Chuveiro de mão, embutido no degrau, com água quente/fria na plataforma de popa', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Saída de emergência pela Gaiuta de proa, com escada de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', '(2) Escotilha para compartimento de proa', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Propulsor de manobra de proa hidráulico (50Hp)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Iluminação de cortesia nos passadiços', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Acesso principal à sala de máquinas através de acesso boreste no cockpit (escadas de aço inoxidável e teca)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Suporte para cabos o no compartimento de proa', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Cabos de atracação (76m)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Perfil para fechamento perimetral para toldos (cockpit, passadiços laterais)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Âncoras de piscina (2 x 90Kg) com 2 correntes (120m cada, diâmetro 13mm)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Acesso bombordo e boreste ao posto de comando flybridge através de degraus fibra de vidro, revestido de teca com guarda-corpos de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Pega mão na sala de máquinas', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Corta combustível de motor e geradores, ativação do sistema de extinção de incêndios', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Roletes para passa cabos, popa (2), proa (4), meia-nau (4)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Mangueira de combate a incêndio com água do mar e lavagem de correntes', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Enrolador de cabo para docagem de 400V', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Porta de saída lateral da cozinha', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Cunhos de aço inoxidável: na popa (4), na meia-nau (2 para cada lado) e na proa (4)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Ferragens de convés em aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Garagem de popa com sistema de içamento/lançamento (rolos, guincho elétrico)', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Plataforma de popa em teca com sistema de elevação eletro-hidráulica com degraus integrados e escada de banho dobrável manual', 'Padrão', 1, true, null),
  ('FY1000', 'Deck Principal', 'Piso em teca', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Porta de correr em vidro temperado na popa com molduras de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Mesa conversível para café/jantar no cockpit com mecanismo de elevação, logotipo e cobertura em aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Sofás de frente (2) em fibra de vidro com estofamento', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Ice-maker', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Iluminação no cockpit', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', '(2) Controle de som com alto-falantes à prova de d''água', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Estação de atracação (2) com coberturas em GRP, espaço de armazenamento para linhas de atracação e pia', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Acesso secundário à sala de máquinas através de uma escotilha e uma escada de aço inoxidável e teca', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Corrimão autoportante (fibra de vidro e vidro)', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Solário de proa', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Área de jantar na proa com sofás (2), mesas (2), porta-copos (2), escotilhas (2) para alojamento de botes salva-vidas', 'Padrão', 1, true, null),
  ('FY1000', 'Praça de Popa/Cockpit', 'Espreguiçadeira na proa com almofadas para banho de sol e porta-copos (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Porta de correr em vidro temperado com acesso ao cockpit com molduras de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Armário com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Refrigerador de gaveta 105 L 24v', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Cortinas na porta de popa e janelas laterais', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Carpete ajustado e revestimento acústico', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Sistima de som Hi-Fi Home cinema 5+1', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Área de estar (sofá em formato de L, poltrona e mesa de café)', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'TV LED de 43" ou equivalente', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'ÁREA DE JANTAR', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Armários com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', '(10) cadeiras', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Mesa de jantar', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Cortinas nas janelas laterais', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Louças de porcelana, copos e talheres de aço inoxidável para 12 pessoas', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Luzes indiretas', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Carpete ajustado e revestimento acústico', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'GALLEY / COZINHA', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Armários com prateleiras e gavetas', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Cooktop de cerâmico com 4 bocas', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Bancada de cerâmica', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Forno combinado elétrico/micro-ondas', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Máquina de lavar louça', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Exaustor coifa com saída externa', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Compactador de lixo', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Porta de saída lateral manual', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Mini Hi-Fi', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Armários suspensos na cozinha', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Cortinas de enrolar', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Geladeira Side by Side 594L 230V', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Pia de aço inoxidável com água quente/fria', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Piso vinílico', 'Padrão', 1, true, null),
  ('FY1000', 'Salão', 'Janela com vigia de aço inoxidável que pode ser aberta', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Painel elétrico', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Bancada dobrável', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Armazenamento', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Piso vinílico', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Máquina lava e seca', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Degraus de madeira para a área da tripulação no convés inferior com corrimãos de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Degraus de madeira para a posição elevada do posto de comando principal com corrimão', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'LOBBY CABINE MASTER', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Carpete ajustado e revestimento acústico', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Degraus de madeira para acesso ao convés inferior com corrimão', 'Padrão', 1, true, null),
  ('FY1000', 'Lobby Tripulação', 'Degraus de madeira para acesso ao comando principal', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Lavatório de cerâmica com estrutura de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Bancada e prateleira de madeira com borda antirrespingo', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Cortinas', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Vaso sanitário', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Painel de controle do vaso sanitário com medidor (3/4 e cheio)', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Janela com vigia de aço inoxidável que pode ser aberta', 'Padrão', 1, true, null),
  ('FY1000', 'Lavabo', 'Piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Parede traseira com isolamento acústico', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', '(2) Criados-mudos com tampo de couro', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Armários com tampo de couro', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Cortinas e coberturas de enrolar nas janelas laterais', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Cofre digital', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Cama de casal com colchão, travesseiros e roupa de cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', '(4) Gavetas embaixo na cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Penteadeira com gaveta, tampo de mármore e otomano', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Cabeceira estofada em tecido', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Carpete ajustado e revestimento acústico', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Sistema de som Hi-Fi Iluminação indireta', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Ventilação natural sob a cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', '(2) Luminárias de leitura', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Sofá', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'TV LED de 43" ou equivalente', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', 'Guarda-roupa com espaço amplo, cabideiro e prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine Master', '(2) Janela com vigias de aço inoxidável que podem ser abertas', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Bancada e prateleira de madeira com borda antirrespingo', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Armários com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Lavatórios de mármore (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Parede de mármore estriado na proa', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Cortinas de enrolar', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Cortina impermeável de enrolar para a janela do chuveiro', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Chuveiro com porta de vidro, piso e assento de mármore', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Painel de controle do vaso sanitário com medidor (3/4 e cheio)', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Vaso sanitário separado por porta de vidro', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Janela com vigias de aço inoxidável que podem ser abertas (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Master', 'Piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Controle do piloto automático', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Barômetro, relógio e higrômetro', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Tomada para acendedor de cigarros (12V)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Controles eletrônicos para embreagem do motor e acelerador com funções de fácil atracação e auto-troll', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Contador eletrônico digital de corrente', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Assento do capitão', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Sistema de monitoramento integrado com tela sensível ao toque (integrado ao sistema de navegação)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Manual Digital Interativo no iPad', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Bússola magnética', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Posição principal do posto de comando com instrumentação completa', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', '(3) Tela sensível ao toque multifuncional para sistema de navegação (radar, chartplotter, GPS, ecosonda, dados dos motores)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Mesa redonda com base de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Indicador de ângulo do leme (integrado com o sistema de navegação)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Janela lateral com abertura basculante (bombordo)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Sofá', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Compartimentos de armazenamento', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Quadro sinóptico com alarmes visuais e acústicos', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Controles de trim (interceptors)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'VHF', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Limpadores de para-brisa (4) com temporizador', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Degraus de madeira e escotilha de vidro temperado deslizante com molduras de aço inoxidável com acesso para o Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Degraus de madeira para a área da tripulação com corrimão', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Degraus de madeira para a área do lobby da cabine master', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Portão de embarque em fibra de vidro', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Bocal de abastecimento de água doce para lavagem proa do convés e lavagem da embarcação na popa', 'Padrão', 1, true, null),
  ('FY1000', 'Comando Principal', 'Guarda-corpo de teca nas muradas laterais', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Acesso ao comando principal através de escadas de madeiras e porta deslizante de vidro temperado com moldura de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Assento do co-piloto', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Capa para a posição do posto de comando e 4 assentos', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Mastro inox para iluminação navegação diurna', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Farol elétrico direcionável na proa', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Sofás independentes com capas', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Hardtop em fibra de vidro com teto de vidro fixo', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Bóia salva-vidas com linha flutuante e bóia luminosa', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Coletes salva-vidas (16)', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Iluminação no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Luzes de navegação', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Piso antiderrapante no convés', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Radar de matriz aberta', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Guarda-corpo perimetral', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Defletor frontal e lateral de policarbonato', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Acesso a bombordo e boreste ao cockpit através de degraus de aço inoxidável e teca, corrimão de aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Farol de busca portátil 12V', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Mastro de bandeira em aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Corrimão em aço inoxidável na popa', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Mastro de sinalização/bandeira em aço inoxidável', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Mesa de teca com capa', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Antena de TV', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Buzina com compressor', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Alto-falantes à prova d''água (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Flybridge', 'Móvel Bar com compartimentos, tampo de corian, pia, grelha e geladeira', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Controles eletrônicos para embreagem do motor e acelerador com funções de fácil acoplamento e velocidade de cruzeiro automática', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Contador digital eletrônico de corrente', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Mini sistema de áudio', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Tela de toque multifuncional para sistema de navegação (radar, chartplotter, GPS, ecosonda, dados dos motores) repetidor', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Tomada 12V', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Assentos do piloto com ajuste para cima/baixo', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Indicador de ângulo do leme', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Segunda posição de comando equipada com instrumentos e alarmes', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Controles de trim (interceptors)', 'Padrão', 1, true, null),
  ('FY1000', 'Comando do Flybridge', 'Rádio VHF', 'Padrão', 1, true, null),
  ('FY1000', 'Lower Deck Lobby', 'Armário com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Lower Deck Lobby', 'Carpete', 'Padrão', 1, true, null),
  ('FY1000', 'Lower Deck Lobby', 'Espelhos', 'Padrão', 1, true, null),
  ('FY1000', 'Lower Deck Lobby', 'Guarda-roupa com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Lower Deck Lobby', 'Degraus de madeira com corrimão que levam ao convés principal', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', '(2) Mesa de cabeceira com gaveta', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Cama de casal com colchão, travesseiros e roupa de cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', '(4) Gavetas embaixo da cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Penteadeira com pufe', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Cabeceira estofada em tecido', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Carpete', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', '(2) Janela com vigias de aço inoxidável com abertura e cortina retrátil', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Iluminação indireta', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Mini sistema de áudio', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Ventilação natural sob a cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Luminárias de leitura (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Cortina padrão', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Tomada de TV', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines VIP (2)', 'Closet com cabideiro', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Armário com prateleiras e gaveta', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Pia de cerâmica com moldura de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Tampo e prateleira de madeira com borda antirrespingo', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Vaso sanitário elétrico', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Janela com vigia de aço inoxidável com abertura', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Cortinas enroláveis e persianas blackout', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Chuveiro com porta de vidro temperado e piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Painel de controle do vaso sanitário com indicador (3/4 e cheio)', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros VIP (2)', 'Piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Cama com armazenamento e gavetas', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', '(2) Criado-mudo com gaveta', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Cama de casal com colchão, travesseiros e roupa de cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Cabeceira estofada em tecido', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Carpete ajustado', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Janela com vigias de aço inoxidável com abertura (2) e cortina retrátil', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Iluminação indireta', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Mini sistema de áudio', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Ventilação natural sob a cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Luminárias de leitura (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Cortinas padrão blackout', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Tomada de tv', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines Hóspedes (2)', 'Guarda-roupa', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Armário com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Pia de cerâmica com moldura de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Tampo e prateleira de madeira com borda antirrespingo', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Vaso sanitário elétrico', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Janela do casco com vigia de aço inoxidável com abertura e cortina retrátil', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Cortinas enroláveis', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Chuveiro com porta de vidro temperado e piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Painel de controle do vaso sanitário com indicador (3/4 e cheio)', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiros Hóspedes (2)', 'Piso de madeira', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Vaso sanitário elétrico com cerâmica', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Armário com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Chuveiro com divisória', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Vigia de aço inoxidável com abertura', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Pia', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro do Capitão', 'Painel de controle do vaso sanitário com indicador (3/4 e cheio)', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Mesa de cabeceira', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Cortina', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Carpete embutido', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Armário', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Cama de solteiro com colchão, travesseiro e cobertor', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Vigia de aço inoxidável com abertura', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Armazenamento sob a cama', 'Padrão', 1, true, null),
  ('FY1000', 'Cabine do Capitão', 'Guarda-roupa', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Vaso sanitário elétrico com cerâmica', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Armário', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Espelho', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Chuveiro', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Vigia de aço inoxidável com abertura', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Pia', 'Padrão', 1, true, null),
  ('FY1000', 'Banheiro Tripulação', 'Painel de controle do vaso sanitário com indicador (3/4 e cheio)', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines da Tripulação (2)', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines da Tripulação (2)', 'Camas (2) com colchões, travesseiros e cobertores', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines da Tripulação (2)', 'Cortina', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines da Tripulação (2)', 'Carpete embutido', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines da Tripulação (2)', 'Vigia de aço inoxidável com abertura', 'Padrão', 1, true, null),
  ('FY1000', 'Cabines da Tripulação (2)', 'Guarda-roupa', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Acesso ao lobby (escadas de madeira)', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Ar-condicionado', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Armário com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Armário com prateleiras', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Área de estar (sofá, mesa de madeira extensível)', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Vigia de aço inoxidável com abertura', 'Padrão', 1, true, null),
  ('FY1000', 'Dinette Tripulação', 'Piso de vinílico', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Acesso à área do cockpit através de uma escotilha e uma escada de aço inoxidável e teca', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Entradas de ar (2) com separadores de névoa', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Gerador elétrico auxiliar (29kW)', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Válvulas de transferência (2) para bombeamento de água de emergência do porão', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Câmeras de monitoramento colorida CCTV (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Filtros de combustível duplos (2) para motores', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Bomba elétrica de porão', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Exaustor elétricos para ventilação (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Extintor de incêndio', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Sistema de extinção de incêndio FM200 na sala de máquinas com controle automático/manual', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Saída de água doce para abastecimento e lavagem', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Indicador de nível do tanque de combustível', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Tanque de combustível em fibra de vidro (9000L) com decantador e descarga', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Iluminação de LED', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Piso antiderrapante em alumínio', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Acesso principal através da abertura à boreste no cockpit (escada de aço inoxidável e teca)', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Gerador elétrico principal (29kW)', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Painel elétrico principal', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Luminária portátil com cabo retrátil', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Antepara à prova de som e à prova d''água', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Escapamentos silenciados abaixo da linha d''água', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Filtros de água (2) para o sistema de arrefecimento do motor', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Filtros de água (2) para o sistema de refrigeração do gerador', 'Padrão', 1, true, null),
  ('FY1000', 'Área Técnica / Sala de Máquinas', 'Dessalinizador (130l/h)', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Acesso a partir da plataforma de popa pela escada dobráveis de fibra de vidro', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Guinchos elétricos para içamento / lançamento de bote/jet-ski', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Portão eletro-hidráulico', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Piso antiderrapante', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'EQUIPAMENTOS DE PROPULSÃO E CONTROLE', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Direção eletro-hidráulica', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Propulsor de manobra de proa hidráulico (50hp)', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Selo mecânico com vedção do eixo sem gotejamento, baixa manutenção', 'Padrão', 1, true, null),
  ('FY1000', 'Garagem', 'Transmissão em V', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas de Estabilização', 'Aletas estabilizadoras em movimento e em velocidade zero (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas de Estabilização', 'Estabilizadores de trim (interceptors)', 'Padrão', 1, true, null),
  ('FY1000', 'Equipamentos Eletrônicos', 'Modem e roteador Wi-Fi', 'Padrão', 1, true, null),
  ('FY1000', 'Equipamentos Eletrônicos', 'Rádio VHF (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Monitoramento', 'Sistema de monitoramento por câmeras na sala de máquinas', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Monitoramento', 'Sistema com tela sensível ao toque integrado ao sistema de navegação', 'Padrão', 1, true, null),
  ('FY1000', 'Navegação', 'Posição principal do piloto automático', 'Padrão', 1, true, null),
  ('FY1000', 'Navegação', 'Tela de toque multifuncional para o sistema de navegação (radar, chartplotter, GPS, sonar, dados dos motores) (3)', 'Padrão', 1, true, null),
  ('FY1000', 'Navegação', 'Repetidor de tela de toque multifuncional para o sistema de navegação (radar, chartplotter, GPS, sonar, dados dos motores)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Extinção de Incêndios', 'Sistema de extinção de incêndios FM200 na sala de máquinas com controle automático/manual', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Extinção de Incêndios', 'Extintores portáteis', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Extinção de Incêndios', 'Manipulo de corta combustível sala de máquinas (desligamento automático de motores e geradores com o sistema de extinção de incêndios, ativação do sistema de extinção de incêndios)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Extinção de Incêndios', 'Sistema de alarme de detecção de fumaça', 'Padrão', 1, true, null),
  ('FY1000', 'Ar-condicionado', 'Sistema de ar-condicionado tropical', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Carregador de bateria automático (2) para baterias de serviço auxiliar de 24V', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Carregador de bateria automático para baterias do motor de 24V', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Gerador auxiliar (29kW)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Bateria de partida do gerador auxiliar de 12V (baixa perda de água)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Carregador de bateria para gerador (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Interruptores de desligamento das baterias: controles manual e remoto', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Caixa de disjuntores', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Disjuntor Carling 100A para alimentação de terra de 240V (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Proteção catódica com ânodos', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Tomadas internas duplas de 120V em cada caixa', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Enrolador de cabo de cais 100A 400V 3 polos + terra (20m)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Aterramento entrada de água do mar e guarda mancebo', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Grupo de baterias de serviço auxiliar de 24V', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Grupo de baterias para o motor de 24V (baixa perda de água)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Iluminação interna/externa do barco em 24V LED', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Inversor 60Hz/120V para geladeira', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Inversor 60Hz/120V para serviços', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Gerador principal (29kW)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Bateria do gerador principal de 12V (baixa perda de água)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Disjuntores manuais de desligamento de bateria (2) para geradores', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Interruptor de bateria elétrica paralela mecânica (cockpit)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema Elétrico', 'Transformador de isolamento trifásico / monofásico, 25KVA (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Porão', 'Bomba elétrica para drenagem do porão (sala de máquinas)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Porão', 'Bombas elétricas, 5 (2 na sala de máquinas, 3 no espaço de acomodação)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Porão', 'Tubo de sucção de emergência do porão (sala de máquinas) através da bomba de arrefecimento do motor', 'Padrão', 1, true, null),
  ('FY1000', 'Sistema de Porão', 'Bomba elétrica polivalente (porão, água cinza, águas negras)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Bomba elétrica automática/manual para esvaziamento do tanque de águas negras (intercambiável com água cinza)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Bomba elétrica automática/manual para sistema de descarga de águas cinzas (intercambiável com tanque de água negra)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Tanques de águas negras (420L) com medidores (3/4 e cheio) e saída externa', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Sistema de vaso sanitário elétrico com água doce', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Bomba autoclave de água doce (240V)', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Bomba autoclave de água doce (24V) com controle eletrônico', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Tanque de água doce de 1320L', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Tanque de água cinza de 330L', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Sistema de combate a incêndio com água do mar e enxágue com corrente', 'Padrão', 1, true, null),
  ('FY1000', 'Sistemas Sanitários e de Água', 'Aquecedores de água 240V (2, 80L + 80L)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Geladeira Extra no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Forno Microondas embutido na Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Máquina de Secar', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Máquina de Lavar', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Icemaker com Reservatório de Água Dedicado no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Forno Elétrico na Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Máquina de Café Embutida na Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Adega para Vinhos na Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Cook top de Indução com 5 bocas na Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Triturador de Resíduos na pia da Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Grill duplo no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Exaustor de ar nos Banheiros', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Entrada de água doce', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Dessalinizador 221 l/h', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Sistema de Extinçao de Incendio Automático', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Inversor de Frequência', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Upgrade de Geradores - 2x 32kw', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Upgrade de Capacidade nos Tanques de Águas Negras - 2x 330l', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Centrifuga de Combustível', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Luzes Submergíveis – 8un', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Equipmanento de Salvatagem (conforme NORMAN)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Lâminas de Sombreamento no Flybridge, com Acionamento Elétrico', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Tendalino de Popa no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Teca com Acabamento na cor preta no Cockpit, Passadiço e Proa', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Tendalino de Proa', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Teca com Acabamento na cor preta no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Mesa em Teca Natural na Proa, Conversível em Solário', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Lixeira no Cockpit', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Tendalino para o Cockpit', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Luzes de Cortesia para a Área Externa', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Ducha na Popa com Água Quente e Fria', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Pintura de Fundo com Tinta Anti-fouling', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Nome da Embarcação em Aço Inox na Popa', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Nome da Embarcação em Aço Inox na Proa', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Farol de Busca Elétrico', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Sofá de Popa Integrado com a Plataforma de Banho', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Tendalino para a Plataforma de Banho', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Cortinas Motorizadas para o Salão', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Porta Automática Para Acesso Principal ao Salão', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Porta Manual a Bombordo no Salão', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Porta Manual a Boreste no Salão', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Cortina na Janela Lateral da Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Divisória Elétrica na Galley', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Telas Contra Mosquitos nas Vigias', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Portinholas Laterais - Bombordo e Boreste', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Cortinas e Blackout Motorizados nas Cabines VIP e Hóspedes', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Cofre Digital na Cabine Master', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Camas de Solteiro nas Cabines de Hóspedes, conversíveis em cama de casal (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Piso em Madeira no Salão', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Luzes de Cortesia e Dimerização para o Interior', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Cortinas e Blackout Motorizados na Cabine Master', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Ar-Condicionado Super Tropical - 156.000 BTU', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Revestimento em Couro no Leme do Comando Principal', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Ponto de Acesso a Wi-Fi e cabo de rede', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'TV 24" na Área da Tripulação', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'TV 49" com Lift Elétrico no Flybridge', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Mirror TV 55" na Cabine Master', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Mirror TV 43" na Cabine Hospedes (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'TV 75" no Salão', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Mirror TV 50" na Cabine VIP (2)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Upgrade Simrad: 4x telas de 24'''' mo Comando Principal; 2x telas NSS EVO3 16" no flybridge, e Antena de Radar Halo 6', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Sonda Digital Simrad', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Tela Repetidora Simrad 16" na Área da Tripulação', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Stern Thurster 40 Hp', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Terceiro Comando no Cockpit', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Indicador de Posição "EPIRB" (Emergency position indicator radiobeacon)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Sistema NAVIOP', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Sistema de Identificação Maritima AIS Simrad NAIS500 (RX-TX)', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Seakeeper NG 18 + NG 9', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Estação de Abastecimento para Tender/Bote na Garagem', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Sistema de Lançamento de Tender/Bote', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Geladeira no hall do lower deck', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Geladeira na área marinheiro', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Enrolador de cabo elétrico', 'Padrão', 1, true, null),
  ('FY1000', 'Opcionais Inclusos', 'Freezer extra 90l no storage de proa', 'Padrão', 1, true, null);

-- ✅ Total de 335 itens do modelo FY1000 inseridos!