// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqxhkaowexieednyazwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxeGhrYW93ZXhpZWVkbnlhendxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNDcwNzcsImV4cCI6MjA3NjYyMzA3N30.JfpG7lXhJjIcGeISeyYK7pQul9LZoqc2eHmsDkSDKeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});